#!/bin/bash

set -e

(cd apt && if [ -s packages.txt ]; then sudo apt update && sudo apt install python3-pip $(cat packages.txt); fi)
(cd pip && if [ -s requirements.txt ]; then pip install -r requirements.txt; fi)
(cd rosdep && sudo cp -r * ${ROSDEP_SOURCE_PATH:-/etc/ros/rosdep}/. && rosdep update)
