#!/usr/bin/env python3

import argparse
import pathlib
import sys

import yaml


def main():
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('-o', '--output-directory', type=pathlib.Path, default='.')
    parser.add_argument('-i', '--install-directory', type=pathlib.Path, default=None)
    parser.add_argument('-p', '--priority', default=99)
    parser.add_argument('-s', '--stem', default='null')
    parser.add_argument('-v', '--os-version', default='ubuntu')
    parser.add_argument('debs', type=pathlib.Path, nargs='+')
    args = parser.parse_args()

    if args.install_directory is None:
        args.install_directory = args.output_directory

    args.output_directory.mkdir(parents=True, exist_ok=True)
    with (args.output_directory / f'{args.stem}.yaml').open('w') as f:
        yaml.safe_dump({deb.name: {args.os_version: []} for deb in args.debs}, f)

    sources_output_directory = args.output_directory / 'sources.list.d'
    sources_output_directory.mkdir(parents=True, exist_ok=True)
    with (sources_output_directory / f'{args.priority}-{args.stem}.list').open('w') as f:
        f.write(f'yaml file://{args.install_directory}/{args.stem}.yaml\n')


if __name__ == '__main__':
    sys.exit(main())
