package_mapping:
  bosdyn.api: bosdyn_api_msgs
  bosdyn.api.docking: bosdyn_api_msgs
  bosdyn.api.graph_nav: bosdyn_graph_nav_api_msgs
  bosdyn.api.spot: bosdyn_spot_api_msgs
  bosdyn.api.spot_cam: bosdyn_spot_cam_api_msgs
