// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/AcquireLeaseResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ACQUIRE_LEASE_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ACQUIRE_LEASE_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/acquire_lease_response_status__struct.h"
// Member 'lease'
#include "bosdyn_msgs/msg/detail/lease__struct.h"
// Member 'lease_owner'
#include "bosdyn_msgs/msg/detail/lease_owner__struct.h"

/// Struct defined in msg/AcquireLeaseResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__AcquireLeaseResponse
{
  /// The AcquireLease response returns the lease for the desired resource if it could be obtained.
  /// If a client is returned a new lease, the client should initiate a
  /// RetainLease bidirectional streaming request immediately after completion
  /// of AcquireLease.
  /// Common response Header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Return status for the request.
  bosdyn_msgs__msg__AcquireLeaseResponseStatus status;
  /// The lease for the resource. Only set if status field == STATUS_OK.
  bosdyn_msgs__msg__Lease lease;
  bool lease_is_set;
  /// The owner for the lease. Set if status field == OK or status field ==
  /// RESOURCE_ALREADY_CLAIMED.
  bosdyn_msgs__msg__LeaseOwner lease_owner;
  bool lease_owner_is_set;
} bosdyn_msgs__msg__AcquireLeaseResponse;

// Struct for a sequence of bosdyn_msgs__msg__AcquireLeaseResponse.
typedef struct bosdyn_msgs__msg__AcquireLeaseResponse__Sequence
{
  bosdyn_msgs__msg__AcquireLeaseResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__AcquireLeaseResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ACQUIRE_LEASE_RESPONSE__STRUCT_H_
