// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ActionWrapperSpotCamLed.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ACTION_WRAPPER_SPOT_CAM_LED__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ACTION_WRAPPER_SPOT_CAM_LED__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'brightnesses'
#include "bosdyn_msgs/msg/detail/key_int32_value_float32__struct.h"

/// Struct defined in msg/ActionWrapperSpotCamLed in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ActionWrapperSpotCamLed
{
  /// There are four LEDs at indices [0, 3]. The brightness for each LED
  /// may be set between [0.0, 1.0], where 0 is off and 1 is full
  /// brightness.
  bosdyn_msgs__msg__KeyInt32ValueFloat32__Sequence brightnesses;
} bosdyn_msgs__msg__ActionWrapperSpotCamLed;

// Struct for a sequence of bosdyn_msgs__msg__ActionWrapperSpotCamLed.
typedef struct bosdyn_msgs__msg__ActionWrapperSpotCamLed__Sequence
{
  bosdyn_msgs__msg__ActionWrapperSpotCamLed * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ActionWrapperSpotCamLed__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ACTION_WRAPPER_SPOT_CAM_LED__STRUCT_H_
