// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ActionAfterLeaseStale.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER_LEASE_STALE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER_LEASE_STALE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'leases'
#include "bosdyn_msgs/msg/detail/lease__struct.h"

/// Struct defined in msg/ActionAfterLeaseStale in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ActionAfterLeaseStale
{
  bosdyn_msgs__msg__Lease__Sequence leases;
} bosdyn_msgs__msg__ActionAfterLeaseStale;

// Struct for a sequence of bosdyn_msgs__msg__ActionAfterLeaseStale.
typedef struct bosdyn_msgs__msg__ActionAfterLeaseStale__Sequence
{
  bosdyn_msgs__msg__ActionAfterLeaseStale * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ActionAfterLeaseStale__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER_LEASE_STALE__STRUCT_H_
