// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ActionAfterControlledMotorsOff.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER_CONTROLLED_MOTORS_OFF__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER_CONTROLLED_MOTORS_OFF__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/ActionAfterControlledMotorsOff in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ActionAfterControlledMotorsOff
{
  uint8_t structure_needs_at_least_one_member;
} bosdyn_msgs__msg__ActionAfterControlledMotorsOff;

// Struct for a sequence of bosdyn_msgs__msg__ActionAfterControlledMotorsOff.
typedef struct bosdyn_msgs__msg__ActionAfterControlledMotorsOff__Sequence
{
  bosdyn_msgs__msg__ActionAfterControlledMotorsOff * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ActionAfterControlledMotorsOff__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER_CONTROLLED_MOTORS_OFF__STRUCT_H_
