// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ActionAfter.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'action'
#include "bosdyn_msgs/msg/detail/action_after_one_of_action__struct.h"
// Member 'after'
#include "builtin_interfaces/msg/detail/duration__struct.h"

/// Struct defined in msg/ActionAfter in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ActionAfter
{
  /// Record an event.
  /// Robot triggers AutoReturn.
  /// After coming to a halt, robot sits and powers off its motors.
  /// Takes priority over AutoReturn and HaltRobot actions.
  /// Robot powers off its computer immediately.
  /// WARNING: This will cause loss of recent data, and may damage the robot or its payloads if
  /// done while the robot is not sitting.
  /// The leases are marked as stale, making the resource available for other clients.
  /// See the LeaseResource message for details.
  bosdyn_msgs__msg__ActionAfterOneOfAction action;
  /// Take the specified action after not hearing from the associated policy_id in this long.
  builtin_interfaces__msg__Duration after;
  bool after_is_set;
} bosdyn_msgs__msg__ActionAfter;

// Struct for a sequence of bosdyn_msgs__msg__ActionAfter.
typedef struct bosdyn_msgs__msg__ActionAfter__Sequence
{
  bosdyn_msgs__msg__ActionAfter * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ActionAfter__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ACTION_AFTER__STRUCT_H_
