// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/AlertDataSeverityLevel.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ALERT_DATA_SEVERITY_LEVEL__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ALERT_DATA_SEVERITY_LEVEL__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'SEVERITY_LEVEL_UNKNOWN'.
/**
  * Do not use. If severity is unknown, must assume issue is
  * highest severity.
 */
enum
{
  bosdyn_msgs__msg__AlertDataSeverityLevel__SEVERITY_LEVEL_UNKNOWN = 0
};

/// Constant 'SEVERITY_LEVEL_INFO'.
/**
  * Informational message that requires no action.
 */
enum
{
  bosdyn_msgs__msg__AlertDataSeverityLevel__SEVERITY_LEVEL_INFO = 1
};

/// Constant 'SEVERITY_LEVEL_WARN'.
/**
  * An error may occur in the future if no action is taken, but no action
  * presently required.
 */
enum
{
  bosdyn_msgs__msg__AlertDataSeverityLevel__SEVERITY_LEVEL_WARN = 2
};

/// Constant 'SEVERITY_LEVEL_ERROR'.
/**
  * Action required. Error fatal to operation.
 */
enum
{
  bosdyn_msgs__msg__AlertDataSeverityLevel__SEVERITY_LEVEL_ERROR = 3
};

/// Constant 'SEVERITY_LEVEL_CRITICAL'.
/**
  * Action required. Severe error that requires immediate
  * attention.
 */
enum
{
  bosdyn_msgs__msg__AlertDataSeverityLevel__SEVERITY_LEVEL_CRITICAL = 4
};

/// Struct defined in msg/AlertDataSeverityLevel in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__AlertDataSeverityLevel
{
  int8_t value;
} bosdyn_msgs__msg__AlertDataSeverityLevel;

// Struct for a sequence of bosdyn_msgs__msg__AlertDataSeverityLevel.
typedef struct bosdyn_msgs__msg__AlertDataSeverityLevel__Sequence
{
  bosdyn_msgs__msg__AlertDataSeverityLevel * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__AlertDataSeverityLevel__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ALERT_DATA_SEVERITY_LEVEL__STRUCT_H_
