// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/AreaCallbackServiceError.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__AREA_CALLBACK_SERVICE_ERROR__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__AREA_CALLBACK_SERVICE_ERROR__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'missing_services'
#include "rosidl_runtime_c/string.h"
// Member 'faulted_services'
#include "bosdyn_msgs/msg/detail/service_fault__struct.h"

/// Struct defined in msg/AreaCallbackServiceError in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__AreaCallbackServiceError
{
  /// Information about problems Area Callback services specifified in a map or on a route.
  /// Area Callback services that were requested but could not be contacted by graph nav.
  /// A service is considered missing if it is either not registered, or if it is registered
  /// but does not respond to a AreaCallbackInformation request.
  rosidl_runtime_c__String__Sequence missing_services;
  /// Area Callback services that were requested but are reporting critical faults.
  bosdyn_msgs__msg__ServiceFault__Sequence faulted_services;
} bosdyn_msgs__msg__AreaCallbackServiceError;

// Struct for a sequence of bosdyn_msgs__msg__AreaCallbackServiceError.
typedef struct bosdyn_msgs__msg__AreaCallbackServiceError__Sequence
{
  bosdyn_msgs__msg__AreaCallbackServiceError * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__AreaCallbackServiceError__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__AREA_CALLBACK_SERVICE_ERROR__STRUCT_H_
