// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/AreaCallbackData.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__AREA_CALLBACK_DATA__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__AREA_CALLBACK_DATA__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'custom_params'
#include "bosdyn_msgs/msg/detail/dict_param__struct.h"

/// Struct defined in msg/AreaCallbackData in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__AreaCallbackData
{
  /// Data for a AreaCallback to be stored in the map
  /// Custom config data used by the service to do its job.
  ///     google.protobuf.Any config_data = 1;
  /// Any other custom parameters to the callback. This will be copied into
  /// custom_params inside the BeginCallback RPC if it exists.
  bosdyn_msgs__msg__DictParam custom_params;
  bool custom_params_is_set;
} bosdyn_msgs__msg__AreaCallbackData;

// Struct for a sequence of bosdyn_msgs__msg__AreaCallbackData.
typedef struct bosdyn_msgs__msg__AreaCallbackData__Sequence
{
  bosdyn_msgs__msg__AreaCallbackData * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__AreaCallbackData__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__AREA_CALLBACK_DATA__STRUCT_H_
