// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ArmParams.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ARM_PARAMS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ARM_PARAMS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/ArmParams in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ArmParams
{
  ///  Parameters common across arm commands.
  /// / Whether or not to disable the body force limiter running on the robot. By default, this is
  /// / on, and the chance that the body falls over because the arm makes contact in the world is
  /// / low. If this is purposely disabled (by setting disable_body_force_limiter to True), the arm
  /// / may be able to accelerate faster, and apply more force to the world and to objects than usual,
  /// / but there is also added risk of the robot falling over.
  bool disable_body_force_limiter;
  bool disable_body_force_limiter_is_set;
} bosdyn_msgs__msg__ArmParams;

// Struct for a sequence of bosdyn_msgs__msg__ArmParams.
typedef struct bosdyn_msgs__msg__ArmParams__Sequence
{
  bosdyn_msgs__msg__ArmParams * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ArmParams__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ARM_PARAMS__STRUCT_H_
