// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/BatteryStateStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BATTERY_STATE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BATTERY_STATE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * The battery is in an unknown / unexpected state.
 */
enum
{
  bosdyn_msgs__msg__BatteryStateStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_MISSING'.
/**
  * The battery is not plugged in or otherwise not talking.
 */
enum
{
  bosdyn_msgs__msg__BatteryStateStatus__STATUS_MISSING = 1
};

/// Constant 'STATUS_CHARGING'.
/**
  * The battery is plugged in to shore power and charging.
 */
enum
{
  bosdyn_msgs__msg__BatteryStateStatus__STATUS_CHARGING = 2
};

/// Constant 'STATUS_DISCHARGING'.
/**
  * The battery is not plugged into shore power and discharging.
 */
enum
{
  bosdyn_msgs__msg__BatteryStateStatus__STATUS_DISCHARGING = 3
};

/// Constant 'STATUS_BOOTING'.
/**
  * The battery was just plugged in and is booting up= 3;
 */
enum
{
  bosdyn_msgs__msg__BatteryStateStatus__STATUS_BOOTING = 4
};

/// Struct defined in msg/BatteryStateStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__BatteryStateStatus
{
  int8_t value;
} bosdyn_msgs__msg__BatteryStateStatus;

// Struct for a sequence of bosdyn_msgs__msg__BatteryStateStatus.
typedef struct bosdyn_msgs__msg__BatteryStateStatus__Sequence
{
  bosdyn_msgs__msg__BatteryStateStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__BatteryStateStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BATTERY_STATE_STATUS__STRUCT_H_
