// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/BatteryChangePoseCommandRequestDirectionHint.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BATTERY_CHANGE_POSE_COMMAND_REQUEST_DIRECTION_HINT__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BATTERY_CHANGE_POSE_COMMAND_REQUEST_DIRECTION_HINT__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'HINT_UNKNOWN'.
/**
  * Unknown direction, just hold still
 */
enum
{
  bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint__HINT_UNKNOWN = 0
};

/// Constant 'HINT_RIGHT'.
/**
  * Roll over right (right feet end up under the robot)
 */
enum
{
  bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint__HINT_RIGHT = 1
};

/// Constant 'HINT_LEFT'.
/**
  * Roll over left (left feet end up under the robot)
 */
enum
{
  bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint__HINT_LEFT = 2
};

/// Struct defined in msg/BatteryChangePoseCommandRequestDirectionHint in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint
{
  int8_t value;
} bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint;

// Struct for a sequence of bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint.
typedef struct bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint__Sequence
{
  bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BATTERY_CHANGE_POSE_COMMAND_REQUEST_DIRECTION_HINT__STRUCT_H_
