// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/BatteryChangePoseCommandRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BATTERY_CHANGE_POSE_COMMAND_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BATTERY_CHANGE_POSE_COMMAND_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'direction_hint'
#include "bosdyn_msgs/msg/detail/battery_change_pose_command_request_direction_hint__struct.h"

/// Struct defined in msg/BatteryChangePoseCommandRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__BatteryChangePoseCommandRequest
{
  bosdyn_msgs__msg__BatteryChangePoseCommandRequestDirectionHint direction_hint;
} bosdyn_msgs__msg__BatteryChangePoseCommandRequest;

// Struct for a sequence of bosdyn_msgs__msg__BatteryChangePoseCommandRequest.
typedef struct bosdyn_msgs__msg__BatteryChangePoseCommandRequest__Sequence
{
  bosdyn_msgs__msg__BatteryChangePoseCommandRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__BatteryChangePoseCommandRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BATTERY_CHANGE_POSE_COMMAND_REQUEST__STRUCT_H_
