// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/BeginCallbackRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BEGIN_CALLBACK_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BEGIN_CALLBACK_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'region_info'
#include "bosdyn_msgs/msg/detail/region_information__struct.h"
// Member 'end_time'
#include "builtin_interfaces/msg/detail/time__struct.h"
// Member 'recorded_data'
#include "bosdyn_msgs/msg/detail/area_callback_data__struct.h"
// Member 'custom_params'
#include "bosdyn_msgs/msg/detail/dict_param__struct.h"

/// Struct defined in msg/BeginCallbackRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__BeginCallbackRequest
{
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// Description of the region we are going to cross.
  bosdyn_msgs__msg__RegionInformation region_info;
  bool region_info_is_set;
  /// The timestamp (in robot time) by which a command must finish executing.
  /// If unset, a AreaCallback implementation may pick a reasonable value.
  builtin_interfaces__msg__Time end_time;
  bool end_time_is_set;
  /// Configuration data associated with this area callback region
  bosdyn_msgs__msg__AreaCallbackData recorded_data;
  bool recorded_data_is_set;
  /// Any other custom parameters to the callback.
  bosdyn_msgs__msg__DictParam custom_params;
  bool custom_params_is_set;
} bosdyn_msgs__msg__BeginCallbackRequest;

// Struct for a sequence of bosdyn_msgs__msg__BeginCallbackRequest.
typedef struct bosdyn_msgs__msg__BeginCallbackRequest__Sequence
{
  bosdyn_msgs__msg__BeginCallbackRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__BeginCallbackRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BEGIN_CALLBACK_REQUEST__STRUCT_H_
