// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/BodyControlParamsRotationSetting.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BODY_CONTROL_PARAMS_ROTATION_SETTING__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BODY_CONTROL_PARAMS_ROTATION_SETTING__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'ROTATION_SETTING_UNKNOWN'.
/**
  * Invalid; do not use.
 */
enum
{
  bosdyn_msgs__msg__BodyControlParamsRotationSetting__ROTATION_SETTING_UNKNOWN = 0
};

/// Constant 'ROTATION_SETTING_OFFSET'.
/**
  * Pitch & Roll are offset with respect to orientation of the footprint.
 */
enum
{
  bosdyn_msgs__msg__BodyControlParamsRotationSetting__ROTATION_SETTING_OFFSET = 1
};

/// Constant 'ROTATION_SETTING_ABSOLUTE'.
/**
  * Pitch & Roll are offset with respect to gravity.
 */
enum
{
  bosdyn_msgs__msg__BodyControlParamsRotationSetting__ROTATION_SETTING_ABSOLUTE = 2
};

/// Struct defined in msg/BodyControlParamsRotationSetting in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__BodyControlParamsRotationSetting
{
  int8_t value;
} bosdyn_msgs__msg__BodyControlParamsRotationSetting;

// Struct for a sequence of bosdyn_msgs__msg__BodyControlParamsRotationSetting.
typedef struct bosdyn_msgs__msg__BodyControlParamsRotationSetting__Sequence
{
  bosdyn_msgs__msg__BodyControlParamsRotationSetting * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__BodyControlParamsRotationSetting__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BODY_CONTROL_PARAMS_ROTATION_SETTING__STRUCT_H_
