// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/BosdynGraphNavState.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BOSDYN_GRAPH_NAV_STATE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BOSDYN_GRAPH_NAV_STATE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'service_name'
// Member 'host'
// Member 'state_name'
// Member 'waypoint_id'
#include "rosidl_runtime_c/string.h"
// Member 'child'
#include "bosdyn_msgs/msg/detail/node__struct.h"

/// Struct defined in msg/BosdynGraphNavState in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__BosdynGraphNavState
{
  /// Get GraphNav state from the robot and save it to the blackboard.
  /// Name of the service to use.
  rosidl_runtime_c__String service_name;
  /// Host machine the service is running on.
  rosidl_runtime_c__String host;
  /// Child node. Children will have access to the state gathered by this node.
  bosdyn_msgs__msg__Node child;
  bool child_is_set;
  /// Name of the bosdyn.api.GetLocalizationStateResponse object in the blackboard. For example,
  /// if this is set to "nav", children can look up "nav.localization.waypoint_id" in the
  /// blackboard to get the waypoint the robot is localized to.
  rosidl_runtime_c__String state_name;
  /// Id of the waypoint that we want the localization to be relative to.
  /// If this is empty, the localization will be relative to the waypoint that the
  /// robot is currently localized to.
  rosidl_runtime_c__String waypoint_id;
} bosdyn_msgs__msg__BosdynGraphNavState;

// Struct for a sequence of bosdyn_msgs__msg__BosdynGraphNavState.
typedef struct bosdyn_msgs__msg__BosdynGraphNavState__Sequence
{
  bosdyn_msgs__msg__BosdynGraphNavState * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__BosdynGraphNavState__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BOSDYN_GRAPH_NAV_STATE__STRUCT_H_
