// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/Bounds.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__BOUNDS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__BOUNDS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/Bounds in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__Bounds
{
  /// Represents bounds on a value, such that lower < value < upper.
  /// If you do not want to specify one side of the bound, set it to
  /// an appropriately large (or small) number.
  double lower;
  double upper;
} bosdyn_msgs__msg__Bounds;

// Struct for a sequence of bosdyn_msgs__msg__Bounds.
typedef struct bosdyn_msgs__msg__Bounds__Sequence
{
  bosdyn_msgs__msg__Bounds * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__Bounds__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__BOUNDS__STRUCT_H_
