// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/CaptureActionId.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__CAPTURE_ACTION_ID__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__CAPTURE_ACTION_ID__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'action_name'
// Member 'group_name'
#include "rosidl_runtime_c/string.h"
// Member 'timestamp'
#include "builtin_interfaces/msg/detail/time__struct.h"

/// Struct defined in msg/CaptureActionId in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__CaptureActionId
{
  /// The CaptureActionId describes the entire capture action for an AcquireData request and will be
  /// used to uniquely identify that full request's set of stored data.
  /// The action name is used to group all pieces of data associated with a single AcquireData
  /// request. The action name must be unique for the given group name, meaning no two actions
  /// with the same group name can have the same action name.
  rosidl_runtime_c__String action_name;
  /// The group name is used to group a "session" of data, such as a mission or a teleop capture
  /// session, which includes multiple capture actions (from multiple AcquireData RPCs).
  rosidl_runtime_c__String group_name;
  /// Time (in the robot's clock) at which this capture was triggered. If the timestamp is not
  /// specified in the AcquireData RPC, the main data acquisition service on robot will populate
  /// the timestamp field with the timestamp of when the RPC was recieved.
  builtin_interfaces__msg__Time timestamp;
  bool timestamp_is_set;
} bosdyn_msgs__msg__CaptureActionId;

// Struct for a sequence of bosdyn_msgs__msg__CaptureActionId.
typedef struct bosdyn_msgs__msg__CaptureActionId__Sequence
{
  bosdyn_msgs__msg__CaptureActionId * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__CaptureActionId__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__CAPTURE_ACTION_ID__STRUCT_H_
