// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/CommonError.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__COMMON_ERROR__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__COMMON_ERROR__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'code'
#include "bosdyn_msgs/msg/detail/common_error_code__struct.h"
// Member 'message'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/CommonError in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__CommonError
{
  /// General error code are returned in the header to facilitate error-handling which is not
  /// message-specific.
  /// This can be used for generic error handlers, aggregation, and trend analysis.
  /// The different error codes that can be returned on a grpc response message.
  bosdyn_msgs__msg__CommonErrorCode code;
  /// Human-readable error description.  Not for programmatic analysis.
  rosidl_runtime_c__String message;
} bosdyn_msgs__msg__CommonError;

// Struct for a sequence of bosdyn_msgs__msg__CommonError.
typedef struct bosdyn_msgs__msg__CommonError__Sequence
{
  bosdyn_msgs__msg__CommonError * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__CommonError__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__COMMON_ERROR__STRUCT_H_
