// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ComputeParameters.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__COMPUTE_PARAMETERS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__COMPUTE_PARAMETERS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'model_name'
#include "rosidl_runtime_c/string.h"
// Member 'reference_images'
#include "bosdyn_msgs/msg/detail/image_capture_and_source__struct.h"
// Member 'custom_params'
#include "bosdyn_msgs/msg/detail/dict_param__struct.h"

/// Struct defined in msg/ComputeParameters in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ComputeParameters
{
  /// Other data that isn't an image.  NetworkComputeBridge service will pass it through
  /// to the remote server so you can do computation on arbitrary data.
  ///     google.protobuf.Any other_data = 3;
  /// Name of the model to be run on the input data.
  rosidl_runtime_c__String model_name;
  /// For some computer vision operations a number of reference images are required along with the
  /// input image.  These images might have been taken months ago, not neccessarilly taken right
  /// now.
  bosdyn_msgs__msg__ImageCaptureAndSource__Sequence reference_images;
  /// Input parameters unique to this worker that do not match any of the above fields.
  bosdyn_msgs__msg__DictParam custom_params;
  bool custom_params_is_set;
} bosdyn_msgs__msg__ComputeParameters;

// Struct for a sequence of bosdyn_msgs__msg__ComputeParameters.
typedef struct bosdyn_msgs__msg__ComputeParameters__Sequence
{
  bosdyn_msgs__msg__ComputeParameters * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ComputeParameters__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__COMPUTE_PARAMETERS__STRUCT_H_
