// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ConditionOperand.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__CONDITION_OPERAND__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__CONDITION_OPERAND__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'type'
#include "bosdyn_msgs/msg/detail/condition_operand_one_of_type__struct.h"

/// Struct defined in msg/ConditionOperand in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ConditionOperand
{
  bosdyn_msgs__msg__ConditionOperandOneOfType type;
} bosdyn_msgs__msg__ConditionOperand;

// Struct for a sequence of bosdyn_msgs__msg__ConditionOperand.
typedef struct bosdyn_msgs__msg__ConditionOperand__Sequence
{
  bosdyn_msgs__msg__ConditionOperand * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ConditionOperand__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__CONDITION_OPERAND__STRUCT_H_
