// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ConfigureRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__CONFIGURE_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__CONFIGURE_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'leases'
#include "bosdyn_msgs/msg/detail/lease__struct.h"
// Member 'params'
#include "bosdyn_msgs/msg/detail/params__struct.h"

/// Struct defined in msg/ConfigureRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ConfigureRequest
{
  /// Configure the AutoReturn system.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// Leases that AutoReturn may use to accomplish its goals when AutoReturn automatically
  /// triggers. If left empty, AutoReturn will not automatically trigger.
  bosdyn_msgs__msg__Lease__Sequence leases;
  /// Parameters to use when AutoReturn automatically triggers.
  bosdyn_msgs__msg__Params params;
  bool params_is_set;
  /// Forget any buffered locations the robot may be remembering. Defaults to false.
  /// Set to true if the robot has just crossed an area it should not traverse in AutoReturn.
  bool clear_buffer;
} bosdyn_msgs__msg__ConfigureRequest;

// Struct for a sequence of bosdyn_msgs__msg__ConfigureRequest.
typedef struct bosdyn_msgs__msg__ConfigureRequest__Sequence
{
  bosdyn_msgs__msg__ConfigureRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ConfigureRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__CONFIGURE_REQUEST__STRUCT_H_
