// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/CustomParamOneOfValue.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__CUSTOM_PARAM_ONE_OF_VALUE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__CUSTOM_PARAM_ONE_OF_VALUE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'VALUE_NOT_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_NOT_SET = 0
};

/// Constant 'VALUE_DICT_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_DICT_VALUE_SET = 1
};

/// Constant 'VALUE_LIST_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_LIST_VALUE_SET = 2
};

/// Constant 'VALUE_INT_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_INT_VALUE_SET = 3
};

/// Constant 'VALUE_DOUBLE_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_DOUBLE_VALUE_SET = 4
};

/// Constant 'VALUE_STRING_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_STRING_VALUE_SET = 5
};

/// Constant 'VALUE_ROI_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_ROI_VALUE_SET = 6
};

/// Constant 'VALUE_BOOL_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_BOOL_VALUE_SET = 7
};

/// Constant 'VALUE_ONE_OF_VALUE_SET'.
enum
{
  bosdyn_msgs__msg__CustomParamOneOfValue__VALUE_ONE_OF_VALUE_SET = 8
};

// Include directives for member types
// Member 'dict_value'
#include "bosdyn_msgs/msg/detail/serialized_message__struct.h"
// Member 'list_value'
#include "bosdyn_msgs/msg/detail/list_param__struct.h"
// Member 'int_value'
#include "bosdyn_msgs/msg/detail/int64_param__struct.h"
// Member 'double_value'
#include "bosdyn_msgs/msg/detail/double_param__struct.h"
// Member 'string_value'
#include "bosdyn_msgs/msg/detail/string_param__struct.h"
// Member 'roi_value'
#include "bosdyn_msgs/msg/detail/region_of_interest_param__struct.h"
// Member 'bool_value'
#include "bosdyn_msgs/msg/detail/bool_param__struct.h"
// Member 'one_of_value'
#include "bosdyn_msgs/msg/detail/one_of_param__struct.h"

/// Struct defined in msg/CustomParamOneOfValue in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__CustomParamOneOfValue
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// Serialized bosdyn_msgs/DictParam to break recursion
  bosdyn_msgs__msg__SerializedMessage dict_value;
  bosdyn_msgs__msg__ListParam list_value;
  bosdyn_msgs__msg__Int64Param int_value;
  bosdyn_msgs__msg__DoubleParam double_value;
  bosdyn_msgs__msg__StringParam string_value;
  bosdyn_msgs__msg__RegionOfInterestParam roi_value;
  bosdyn_msgs__msg__BoolParam bool_value;
  bosdyn_msgs__msg__OneOfParam one_of_value;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t value_choice;
} bosdyn_msgs__msg__CustomParamOneOfValue;

// Struct for a sequence of bosdyn_msgs__msg__CustomParamOneOfValue.
typedef struct bosdyn_msgs__msg__CustomParamOneOfValue__Sequence
{
  bosdyn_msgs__msg__CustomParamOneOfValue * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__CustomParamOneOfValue__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__CUSTOM_PARAM_ONE_OF_VALUE__STRUCT_H_
