// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DataAcquisitionCompletionBehavior.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DATA_ACQUISITION_COMPLETION_BEHAVIOR__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DATA_ACQUISITION_COMPLETION_BEHAVIOR__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'COMPLETE_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__DataAcquisitionCompletionBehavior__COMPLETE_UNKNOWN = 0
};

/// Constant 'COMPLETE_AFTER_SAVED'.
/**
  * Node is complete after all data has been saved.
 */
enum
{
  bosdyn_msgs__msg__DataAcquisitionCompletionBehavior__COMPLETE_AFTER_SAVED = 1
};

/// Constant 'COMPLETE_AFTER_ACQUIRED'.
/**
  * Node is complete after all data is acquired, but before processing and storage.
  * This allows the robot to continue on with the mission sooner, but
  * it will be unaware of failures in processing or storage.
 */
enum
{
  bosdyn_msgs__msg__DataAcquisitionCompletionBehavior__COMPLETE_AFTER_ACQUIRED = 2
};

/// Struct defined in msg/DataAcquisitionCompletionBehavior in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DataAcquisitionCompletionBehavior
{
  int8_t value;
} bosdyn_msgs__msg__DataAcquisitionCompletionBehavior;

// Struct for a sequence of bosdyn_msgs__msg__DataAcquisitionCompletionBehavior.
typedef struct bosdyn_msgs__msg__DataAcquisitionCompletionBehavior__Sequence
{
  bosdyn_msgs__msg__DataAcquisitionCompletionBehavior * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DataAcquisitionCompletionBehavior__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DATA_ACQUISITION_COMPLETION_BEHAVIOR__STRUCT_H_
