// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DataChunk.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DATA_CHUNK__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DATA_CHUNK__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'data'
#include "rosidl_runtime_c/primitives_sequence.h"

/// Struct defined in msg/DataChunk in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DataChunk
{
  /// Represents a chunk of (possibly serialized) data.
  /// Chunks will be concatenated together to produce a datagram.
  /// This is to avoid size limit restrictions in grpc implementations.
  /// The total size in bytes of the datagram that this chunk is a part of.
  uint64_t total_size;
  /// Bytes in this data chunk. Bytes are sent sequentially.
  rosidl_runtime_c__octet__Sequence data;
} bosdyn_msgs__msg__DataChunk;

// Struct for a sequence of bosdyn_msgs__msg__DataChunk.
typedef struct bosdyn_msgs__msg__DataChunk__Sequence
{
  bosdyn_msgs__msg__DataChunk * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DataChunk__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DATA_CHUNK__STRUCT_H_
