// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DefineBlackboard.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DEFINE_BLACKBOARD__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DEFINE_BLACKBOARD__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'blackboard_variables'
#include "bosdyn_msgs/msg/detail/key_value__struct.h"
// Member 'child'
#include "bosdyn_msgs/msg/detail/node__struct.h"

/// Struct defined in msg/DefineBlackboard in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DefineBlackboard
{
  /// Defines new blackboard variables within the scope of the child. Shadows blackboard
  /// variables in the parent scope.
  /// The list of variables that should be defined for this subtree,
  /// with initial values.
  bosdyn_msgs__msg__KeyValue__Sequence blackboard_variables;
  /// The blackboard variables will only persist in the subtree defined by this
  /// child node. The child's tick() will be called on the child until it
  /// returns either SUCCESS or FAILURE.
  bosdyn_msgs__msg__Node child;
  bool child_is_set;
} bosdyn_msgs__msg__DefineBlackboard;

// Struct for a sequence of bosdyn_msgs__msg__DefineBlackboard.
typedef struct bosdyn_msgs__msg__DefineBlackboard__Sequence
{
  bosdyn_msgs__msg__DefineBlackboard * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DefineBlackboard__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DEFINE_BLACKBOARD__STRUCT_H_
