// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DeletePageStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DELETE_PAGE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DELETE_PAGE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'page_id'
#include "rosidl_runtime_c/string.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/delete_page_status_status__struct.h"

/// Struct defined in msg/DeletePageStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DeletePageStatus
{
  rosidl_runtime_c__String page_id;
  bosdyn_msgs__msg__DeletePageStatusStatus status;
} bosdyn_msgs__msg__DeletePageStatus;

// Struct for a sequence of bosdyn_msgs__msg__DeletePageStatus.
typedef struct bosdyn_msgs__msg__DeletePageStatus__Sequence
{
  bosdyn_msgs__msg__DeletePageStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DeletePageStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DELETE_PAGE_STATUS__STRUCT_H_
