// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DeregisterEstopEndpointResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DEREGISTER_ESTOP_ENDPOINT_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DEREGISTER_ESTOP_ENDPOINT_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'request'
#include "bosdyn_msgs/msg/detail/deregister_estop_endpoint_request__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/deregister_estop_endpoint_response_status__struct.h"

/// Struct defined in msg/DeregisterEstopEndpointResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DeregisterEstopEndpointResponse
{
  /// Response to E-Stop endpoint  deregistration request.
  /// Common resonse header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Copy of the initial request.
  bosdyn_msgs__msg__DeregisterEstopEndpointRequest request;
  bool request_is_set;
  /// Status code for the response.
  bosdyn_msgs__msg__DeregisterEstopEndpointResponseStatus status;
} bosdyn_msgs__msg__DeregisterEstopEndpointResponse;

// Struct for a sequence of bosdyn_msgs__msg__DeregisterEstopEndpointResponse.
typedef struct bosdyn_msgs__msg__DeregisterEstopEndpointResponse__Sequence
{
  bosdyn_msgs__msg__DeregisterEstopEndpointResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DeregisterEstopEndpointResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DEREGISTER_ESTOP_ENDPOINT_RESPONSE__STRUCT_H_
