// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DescriptorBlockOneOfDescriptorType.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DESCRIPTOR_BLOCK_ONE_OF_DESCRIPTOR_TYPE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DESCRIPTOR_BLOCK_ONE_OF_DESCRIPTOR_TYPE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'DESCRIPTORTYPE_NOT_SET'.
enum
{
  bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__DESCRIPTORTYPE_NOT_SET = 0
};

/// Constant 'DESCRIPTORTYPE_FILE_DESCRIPTOR_SET'.
enum
{
  bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__DESCRIPTORTYPE_FILE_DESCRIPTOR_SET = 1
};

/// Constant 'DESCRIPTORTYPE_SERIES_DESCRIPTOR_SET'.
enum
{
  bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__DESCRIPTORTYPE_SERIES_DESCRIPTOR_SET = 2
};

/// Constant 'DESCRIPTORTYPE_SERIES_BLOCK_INDEX_SET'.
enum
{
  bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__DESCRIPTORTYPE_SERIES_BLOCK_INDEX_SET = 3
};

/// Constant 'DESCRIPTORTYPE_FILE_INDEX_SET'.
enum
{
  bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__DESCRIPTORTYPE_FILE_INDEX_SET = 4
};

// Include directives for member types
// Member 'file_descriptor'
#include "bosdyn_msgs/msg/detail/file_format_descriptor__struct.h"
// Member 'series_descriptor'
#include "bosdyn_msgs/msg/detail/series_descriptor__struct.h"
// Member 'series_block_index'
#include "bosdyn_msgs/msg/detail/series_block_index__struct.h"
// Member 'file_index'
#include "bosdyn_msgs/msg/detail/file_index__struct.h"

/// Struct defined in msg/DescriptorBlockOneOfDescriptorType in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType
{
  /// ONEOF MESSAGE  Only one of the following can be set
  bosdyn_msgs__msg__FileFormatDescriptor file_descriptor;
  bosdyn_msgs__msg__SeriesDescriptor series_descriptor;
  bosdyn_msgs__msg__SeriesBlockIndex series_block_index;
  bosdyn_msgs__msg__FileIndex file_index;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t descriptor_type_choice;
} bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType;

// Struct for a sequence of bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType.
typedef struct bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__Sequence
{
  bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DescriptorBlockOneOfDescriptorType__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DESCRIPTOR_BLOCK_ONE_OF_DESCRIPTOR_TYPE__STRUCT_H_
