// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DockStateLinkStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DOCK_STATE_LINK_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DOCK_STATE_LINK_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'LINK_STATUS_UNKNOWN'.
/**
  * Unknown or Not applicable
 */
enum
{
  bosdyn_msgs__msg__DockStateLinkStatus__LINK_STATUS_UNKNOWN = 0
};

/// Constant 'LINK_STATUS_DETECTING'.
/**
  * The link status is being detected
 */
enum
{
  bosdyn_msgs__msg__DockStateLinkStatus__LINK_STATUS_DETECTING = 1
};

/// Constant 'LINK_STATUS_CONNECTED'.
/**
  * The link is detected as connected
 */
enum
{
  bosdyn_msgs__msg__DockStateLinkStatus__LINK_STATUS_CONNECTED = 2
};

/// Constant 'LINK_STATUS_ERROR'.
/**
  * The link could not be detected
 */
enum
{
  bosdyn_msgs__msg__DockStateLinkStatus__LINK_STATUS_ERROR = 3
};

/// Struct defined in msg/DockStateLinkStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DockStateLinkStatus
{
  int8_t value;
} bosdyn_msgs__msg__DockStateLinkStatus;

// Struct for a sequence of bosdyn_msgs__msg__DockStateLinkStatus.
typedef struct bosdyn_msgs__msg__DockStateLinkStatus__Sequence
{
  bosdyn_msgs__msg__DockStateLinkStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DockStateLinkStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DOCK_STATE_LINK_STATUS__STRUCT_H_
