// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DownloadGraphResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DOWNLOAD_GRAPH_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DOWNLOAD_GRAPH_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'graph'
#include "bosdyn_msgs/msg/detail/graph__struct.h"

/// Struct defined in msg/DownloadGraphResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DownloadGraphResponse
{
  /// The DownloadGraph response message includes the current graph on the robot.
  /// Common request header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// The structure of the graph.
  bosdyn_msgs__msg__Graph graph;
  bool graph_is_set;
} bosdyn_msgs__msg__DownloadGraphResponse;

// Struct for a sequence of bosdyn_msgs__msg__DownloadGraphResponse.
typedef struct bosdyn_msgs__msg__DownloadGraphResponse__Sequence
{
  bosdyn_msgs__msg__DownloadGraphResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DownloadGraphResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DOWNLOAD_GRAPH_RESPONSE__STRUCT_H_
