// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/DrawableProperties.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__DRAWABLE_PROPERTIES__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__DRAWABLE_PROPERTIES__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'color'
#include "bosdyn_msgs/msg/detail/drawable_properties_color__struct.h"
// Member 'label'
// Member 'frame_name_drawable'
#include "rosidl_runtime_c/string.h"
// Member 'drawable'
#include "bosdyn_msgs/msg/detail/drawable_properties_one_of_drawable__struct.h"

/// Struct defined in msg/DrawableProperties in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__DrawableProperties
{
  /// The drawing and visualization information for a world object.
  /// RGBA values for color ranging from [0,255] for R/G/B, and [0,1] for A.
  /// Color of the object.
  bosdyn_msgs__msg__DrawablePropertiesColor color;
  bool color_is_set;
  /// Label to be drawn at the origin of the object.
  rosidl_runtime_c__String label;
  /// Drawn objects in wireframe.
  bool wireframe;
  /// The object to draw, e.g. a Sphere.
  bosdyn_msgs__msg__DrawablePropertiesOneOfDrawable drawable;
  /// The frame name for the drawable object. This will optionally be
  /// included in the frame tree snapshot.
  rosidl_runtime_c__String frame_name_drawable;
} bosdyn_msgs__msg__DrawableProperties;

// Struct for a sequence of bosdyn_msgs__msg__DrawableProperties.
typedef struct bosdyn_msgs__msg__DrawableProperties__Sequence
{
  bosdyn_msgs__msg__DrawableProperties * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__DrawableProperties__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__DRAWABLE_PROPERTIES__STRUCT_H_
