// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/EndCallbackResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__END_CALLBACK_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__END_CALLBACK_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * UNKNOWN should never be used.
 */
enum
{
  bosdyn_msgs__msg__EndCallbackResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * The AreaCallback has cleanly ended.
 */
enum
{
  bosdyn_msgs__msg__EndCallbackResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_INVALID_COMMAND_ID'.
/**
  * The request command id does not exist or is no longer executing.
 */
enum
{
  bosdyn_msgs__msg__EndCallbackResponseStatus__STATUS_INVALID_COMMAND_ID = 2
};

/// Constant 'STATUS_SHUTDOWN_CALLBACK_FAILED'.
/**
  * Shutting down the callback failed. The callback worker thread did not respond to shutdown
  * signal.
 */
enum
{
  bosdyn_msgs__msg__EndCallbackResponseStatus__STATUS_SHUTDOWN_CALLBACK_FAILED = 3
};

/// Struct defined in msg/EndCallbackResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__EndCallbackResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__EndCallbackResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__EndCallbackResponseStatus.
typedef struct bosdyn_msgs__msg__EndCallbackResponseStatus__Sequence
{
  bosdyn_msgs__msg__EndCallbackResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__EndCallbackResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__END_CALLBACK_RESPONSE_STATUS__STRUCT_H_
