// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/EstablishSessionRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ESTABLISH_SESSION_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ESTABLISH_SESSION_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'leases'
#include "bosdyn_msgs/msg/detail/lease__struct.h"

/// Struct defined in msg/EstablishSessionRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__EstablishSessionRequest
{
  /// Information to initialize a session to the remote service
  /// for a particular mission node.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// All leases that the remote service may need.
  bosdyn_msgs__msg__Lease__Sequence leases;
} bosdyn_msgs__msg__EstablishSessionRequest;

// Struct for a sequence of bosdyn_msgs__msg__EstablishSessionRequest.
typedef struct bosdyn_msgs__msg__EstablishSessionRequest__Sequence
{
  bosdyn_msgs__msg__EstablishSessionRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__EstablishSessionRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ESTABLISH_SESSION_REQUEST__STRUCT_H_
