// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/EstopStopLevel.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ESTOP_STOP_LEVEL__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ESTOP_STOP_LEVEL__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'ESTOP_LEVEL_UNKNOWN'.
/**
  * The state of the E-Stop system.
  * Invalid stop level.
 */
enum
{
  bosdyn_msgs__msg__EstopStopLevel__ESTOP_LEVEL_UNKNOWN = 0
};

/// Constant 'ESTOP_LEVEL_CUT'.
/**
  * Immediately cut power to the actuators.
 */
enum
{
  bosdyn_msgs__msg__EstopStopLevel__ESTOP_LEVEL_CUT = 1
};

/// Constant 'ESTOP_LEVEL_SETTLE_THEN_CUT'.
/**
  * Prepare for loss of actuator power, then cut power.
 */
enum
{
  bosdyn_msgs__msg__EstopStopLevel__ESTOP_LEVEL_SETTLE_THEN_CUT = 2
};

/// Constant 'ESTOP_LEVEL_NONE'.
/**
  * No-stop level. The endpoint believes the robot is safe to operate.
 */
enum
{
  bosdyn_msgs__msg__EstopStopLevel__ESTOP_LEVEL_NONE = 3
};

/// Struct defined in msg/EstopStopLevel in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__EstopStopLevel
{
  int8_t value;
} bosdyn_msgs__msg__EstopStopLevel;

// Struct for a sequence of bosdyn_msgs__msg__EstopStopLevel.
typedef struct bosdyn_msgs__msg__EstopStopLevel__Sequence
{
  bosdyn_msgs__msg__EstopStopLevel * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__EstopStopLevel__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ESTOP_STOP_LEVEL__STRUCT_H_
