// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/FanPowerCommandResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__FAN_POWER_COMMAND_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__FAN_POWER_COMMAND_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * Status is not specified.
 */
enum
{
  bosdyn_msgs__msg__FanPowerCommandResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Fan Power command succeeded. May still get overriden later in duration
 */
enum
{
  bosdyn_msgs__msg__FanPowerCommandResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_TEMPERATURE_TOO_HIGH'.
/**
  * ERROR: Fan Power command rejected because temperature above safe threshold
 */
enum
{
  bosdyn_msgs__msg__FanPowerCommandResponseStatus__STATUS_TEMPERATURE_TOO_HIGH = 2
};

/// Struct defined in msg/FanPowerCommandResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__FanPowerCommandResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__FanPowerCommandResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__FanPowerCommandResponseStatus.
typedef struct bosdyn_msgs__msg__FanPowerCommandResponseStatus__Sequence
{
  bosdyn_msgs__msg__FanPowerCommandResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__FanPowerCommandResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__FAN_POWER_COMMAND_RESPONSE_STATUS__STRUCT_H_
