// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/FullBodyCommandRequestOneOfCommand.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__FULL_BODY_COMMAND_REQUEST_ONE_OF_COMMAND__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__FULL_BODY_COMMAND_REQUEST_ONE_OF_COMMAND__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'COMMAND_NOT_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_NOT_SET = 0
};

/// Constant 'COMMAND_STOP_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_STOP_REQUEST_SET = 1
};

/// Constant 'COMMAND_FREEZE_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_FREEZE_REQUEST_SET = 2
};

/// Constant 'COMMAND_SELFRIGHT_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_SELFRIGHT_REQUEST_SET = 3
};

/// Constant 'COMMAND_SAFE_POWER_OFF_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_SAFE_POWER_OFF_REQUEST_SET = 4
};

/// Constant 'COMMAND_BATTERY_CHANGE_POSE_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_BATTERY_CHANGE_POSE_REQUEST_SET = 5
};

/// Constant 'COMMAND_PAYLOAD_ESTIMATION_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_PAYLOAD_ESTIMATION_REQUEST_SET = 6
};

/// Constant 'COMMAND_CONSTRAINED_MANIPULATION_REQUEST_SET'.
enum
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__COMMAND_CONSTRAINED_MANIPULATION_REQUEST_SET = 7
};

// Include directives for member types
// Member 'stop_request'
#include "bosdyn_msgs/msg/detail/stop_command_request__struct.h"
// Member 'freeze_request'
#include "bosdyn_msgs/msg/detail/freeze_command_request__struct.h"
// Member 'selfright_request'
#include "bosdyn_msgs/msg/detail/self_right_command_request__struct.h"
// Member 'safe_power_off_request'
#include "bosdyn_msgs/msg/detail/safe_power_off_command_request__struct.h"
// Member 'battery_change_pose_request'
#include "bosdyn_msgs/msg/detail/battery_change_pose_command_request__struct.h"
// Member 'payload_estimation_request'
#include "bosdyn_msgs/msg/detail/payload_estimation_command_request__struct.h"
// Member 'constrained_manipulation_request'
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request__struct.h"

/// Struct defined in msg/FullBodyCommandRequestOneOfCommand in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// Command to stop the robot.
  bosdyn_msgs__msg__StopCommandRequest stop_request;
  /// Command to freeze all joints of the robot.
  bosdyn_msgs__msg__FreezeCommandRequest freeze_request;
  /// Command to self-right the robot to a ready position.
  bosdyn_msgs__msg__SelfRightCommandRequest selfright_request;
  /// Command to safely power off the robot.
  bosdyn_msgs__msg__SafePowerOffCommandRequest safe_power_off_request;
  /// Command to put the robot in a position to easily change the battery.
  bosdyn_msgs__msg__BatteryChangePoseCommandRequest battery_change_pose_request;
  /// Command to perform payload mass property estimation
  bosdyn_msgs__msg__PayloadEstimationCommandRequest payload_estimation_request;
  /// Command to perform full body constrained manipulation moves
  bosdyn_msgs__msg__ConstrainedManipulationCommandRequest constrained_manipulation_request;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t command_choice;
} bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand;

// Struct for a sequence of bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand.
typedef struct bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__Sequence
{
  bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__FullBodyCommandRequestOneOfCommand__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__FULL_BODY_COMMAND_REQUEST_ONE_OF_COMMAND__STRUCT_H_
