// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetServiceInfoResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_SERVICE_INFO_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_SERVICE_INFO_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'capabilities'
#include "bosdyn_msgs/msg/detail/acquisition_capability_list__struct.h"

/// Struct defined in msg/GetServiceInfoResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetServiceInfoResponse
{
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// List of capabilities that the data acquisition (plugin) service can
  /// collect and save data for.
  bosdyn_msgs__msg__AcquisitionCapabilityList capabilities;
  bool capabilities_is_set;
} bosdyn_msgs__msg__GetServiceInfoResponse;

// Struct for a sequence of bosdyn_msgs__msg__GetServiceInfoResponse.
typedef struct bosdyn_msgs__msg__GetServiceInfoResponse__Sequence
{
  bosdyn_msgs__msg__GetServiceInfoResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetServiceInfoResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_SERVICE_INFO_RESPONSE__STRUCT_H_
