// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetLEDBrightnessResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_LED_BRIGHTNESS_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_LED_BRIGHTNESS_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'brightnesses'
#include "rosidl_runtime_c/primitives_sequence.h"

/// Struct defined in msg/GetLEDBrightnessResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetLEDBrightnessResponse
{
  /// Describes the current brightnesses of all LEDs.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Brightness [0, 1] of the LED located at indices [0, 3].
  rosidl_runtime_c__float__Sequence brightnesses;
} bosdyn_msgs__msg__GetLEDBrightnessResponse;

// Struct for a sequence of bosdyn_msgs__msg__GetLEDBrightnessResponse.
typedef struct bosdyn_msgs__msg__GetLEDBrightnessResponse__Sequence
{
  bosdyn_msgs__msg__GetLEDBrightnessResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetLEDBrightnessResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_LED_BRIGHTNESS_RESPONSE__STRUCT_H_
