// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetPointCloudResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_POINT_CLOUD_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_POINT_CLOUD_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'point_cloud_responses'
#include "bosdyn_msgs/msg/detail/point_cloud_response__struct.h"

/// Struct defined in msg/GetPointCloudResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetPointCloudResponse
{
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// The resulting point clouds for each requested source.
  bosdyn_msgs__msg__PointCloudResponse__Sequence point_cloud_responses;
} bosdyn_msgs__msg__GetPointCloudResponse;

// Struct for a sequence of bosdyn_msgs__msg__GetPointCloudResponse.
typedef struct bosdyn_msgs__msg__GetPointCloudResponse__Sequence
{
  bosdyn_msgs__msg__GetPointCloudResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetPointCloudResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_POINT_CLOUD_RESPONSE__STRUCT_H_
