// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetMissionResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_MISSION_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_MISSION_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'root'
#include "bosdyn_msgs/msg/detail/node__struct.h"

/// Struct defined in msg/GetMissionResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetMissionResponse
{
  /// Responding with the mission as it was loaded in LoadMission.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Root node of the mission loaded.
  /// Unset if no mission has been loaded.
  bosdyn_msgs__msg__Node root;
  bool root_is_set;
  /// Mission ID as reported in MissionInfo. -1 if no mission has been loaded.
  int64_t id;
} bosdyn_msgs__msg__GetMissionResponse;

// Struct for a sequence of bosdyn_msgs__msg__GetMissionResponse.
typedef struct bosdyn_msgs__msg__GetMissionResponse__Sequence
{
  bosdyn_msgs__msg__GetMissionResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetMissionResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_MISSION_RESPONSE__STRUCT_H_
