// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetDataIndexRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_DATA_INDEX_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_DATA_INDEX_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'data_query'
#include "bosdyn_msgs/msg/detail/data_query__struct.h"

/// Struct defined in msg/GetDataIndexRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetDataIndexRequest
{
  /// GRPC response with requested data index information.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  bosdyn_msgs__msg__DataQuery data_query;
  bool data_query_is_set;
} bosdyn_msgs__msg__GetDataIndexRequest;

// Struct for a sequence of bosdyn_msgs__msg__GetDataIndexRequest.
typedef struct bosdyn_msgs__msg__GetDataIndexRequest__Sequence
{
  bosdyn_msgs__msg__GetDataIndexRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetDataIndexRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_DATA_INDEX_REQUEST__STRUCT_H_
