// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetStateResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_STATE_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_STATE_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'state'
#include "bosdyn_msgs/msg/detail/state__struct.h"

/// Struct defined in msg/GetStateResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetStateResponse
{
  /// Response to a GetStateRequest.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// The requested mission state.
  bosdyn_msgs__msg__State state;
  bool state_is_set;
} bosdyn_msgs__msg__GetStateResponse;

// Struct for a sequence of bosdyn_msgs__msg__GetStateResponse.
typedef struct bosdyn_msgs__msg__GetStateResponse__Sequence
{
  bosdyn_msgs__msg__GetStateResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetStateResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_STATE_RESPONSE__STRUCT_H_
