// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GetVisibleCamerasResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GET_VISIBLE_CAMERAS_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GET_VISIBLE_CAMERAS_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'streams'
#include "bosdyn_msgs/msg/detail/get_visible_cameras_response_stream__struct.h"

/// Struct defined in msg/GetVisibleCamerasResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GetVisibleCamerasResponse
{
  /// Description of the parameters and locations of each camera in the
  /// current video stream.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// The location and camera parameters for a single camera.
  /// List of all camera streams visible in the current video stream.
  bosdyn_msgs__msg__GetVisibleCamerasResponseStream__Sequence streams;
} bosdyn_msgs__msg__GetVisibleCamerasResponse;

// Struct for a sequence of bosdyn_msgs__msg__GetVisibleCamerasResponse.
typedef struct bosdyn_msgs__msg__GetVisibleCamerasResponse__Sequence
{
  bosdyn_msgs__msg__GetVisibleCamerasResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GetVisibleCamerasResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GET_VISIBLE_CAMERAS_RESPONSE__STRUCT_H_
