// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GripperCameraGetParamRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GRIPPER_CAMERA_GET_PARAM_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GRIPPER_CAMERA_GET_PARAM_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"

/// Struct defined in msg/GripperCameraGetParamRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GripperCameraGetParamRequest
{
  /// The GripperCameraGetParam request message queries the robot for the current gripper sensor
  /// parameters.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
} bosdyn_msgs__msg__GripperCameraGetParamRequest;

// Struct for a sequence of bosdyn_msgs__msg__GripperCameraGetParamRequest.
typedef struct bosdyn_msgs__msg__GripperCameraGetParamRequest__Sequence
{
  bosdyn_msgs__msg__GripperCameraGetParamRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GripperCameraGetParamRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GRIPPER_CAMERA_GET_PARAM_REQUEST__STRUCT_H_
