// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GripperCommandRequestOneOfCommand.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GRIPPER_COMMAND_REQUEST_ONE_OF_COMMAND__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GRIPPER_COMMAND_REQUEST_ONE_OF_COMMAND__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'COMMAND_NOT_SET'.
enum
{
  bosdyn_msgs__msg__GripperCommandRequestOneOfCommand__COMMAND_NOT_SET = 0
};

/// Constant 'COMMAND_CLAW_GRIPPER_COMMAND_SET'.
enum
{
  bosdyn_msgs__msg__GripperCommandRequestOneOfCommand__COMMAND_CLAW_GRIPPER_COMMAND_SET = 1
};

// Include directives for member types
// Member 'claw_gripper_command'
#include "bosdyn_msgs/msg/detail/claw_gripper_command_request__struct.h"

/// Struct defined in msg/GripperCommandRequestOneOfCommand in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GripperCommandRequestOneOfCommand
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// Control opening and closing the gripper.
  bosdyn_msgs__msg__ClawGripperCommandRequest claw_gripper_command;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t command_choice;
} bosdyn_msgs__msg__GripperCommandRequestOneOfCommand;

// Struct for a sequence of bosdyn_msgs__msg__GripperCommandRequestOneOfCommand.
typedef struct bosdyn_msgs__msg__GripperCommandRequestOneOfCommand__Sequence
{
  bosdyn_msgs__msg__GripperCommandRequestOneOfCommand * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GripperCommandRequestOneOfCommand__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GRIPPER_COMMAND_REQUEST_ONE_OF_COMMAND__STRUCT_H_
