// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/GripperCameraGetParamResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__GRIPPER_CAMERA_GET_PARAM_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__GRIPPER_CAMERA_GET_PARAM_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'params'
#include "bosdyn_msgs/msg/detail/gripper_camera_params__struct.h"

/// Struct defined in msg/GripperCameraGetParamResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__GripperCameraGetParamResponse
{
  /// The GripperCameraGetParam response message contains the current gripper sensor parameters.
  /// Gripper sensor parameters do not persist across reboots.
  /// Common request header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  bosdyn_msgs__msg__GripperCameraParams params;
  bool params_is_set;
} bosdyn_msgs__msg__GripperCameraGetParamResponse;

// Struct for a sequence of bosdyn_msgs__msg__GripperCameraGetParamResponse.
typedef struct bosdyn_msgs__msg__GripperCameraGetParamResponse__Sequence
{
  bosdyn_msgs__msg__GripperCameraGetParamResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__GripperCameraGetParamResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__GRIPPER_CAMERA_GET_PARAM_RESPONSE__STRUCT_H_
