// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ICEServerIcetransport.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ICE_SERVER_ICETRANSPORT__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ICE_SERVER_ICETRANSPORT__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'TRANSPORT_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__ICEServerIcetransport__TRANSPORT_UNKNOWN = 0
};

/// Constant 'TRANSPORT_UDP'.
enum
{
  bosdyn_msgs__msg__ICEServerIcetransport__TRANSPORT_UDP = 1
};

/// Constant 'TRANSPORT_TCP'.
enum
{
  bosdyn_msgs__msg__ICEServerIcetransport__TRANSPORT_TCP = 2
};

/// Struct defined in msg/ICEServerIcetransport in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ICEServerIcetransport
{
  int8_t value;
} bosdyn_msgs__msg__ICEServerIcetransport;

// Struct for a sequence of bosdyn_msgs__msg__ICEServerIcetransport.
typedef struct bosdyn_msgs__msg__ICEServerIcetransport__Sequence
{
  bosdyn_msgs__msg__ICEServerIcetransport * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ICEServerIcetransport__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ICE_SERVER_ICETRANSPORT__STRUCT_H_
