// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ImageResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__IMAGE_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__IMAGE_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'shot'
#include "bosdyn_msgs/msg/detail/image_capture__struct.h"
// Member 'source'
#include "bosdyn_msgs/msg/detail/image_source__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/image_response_status__struct.h"
// Member 'custom_param_error'
#include "bosdyn_msgs/msg/detail/custom_param_error__struct.h"

/// Struct defined in msg/ImageResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ImageResponse
{
  /// The image response for each request, that includes image data and image source information.
  /// The image capture contains the image data and information about the state of the camera and robot
  /// at the time the image was collected.
  bosdyn_msgs__msg__ImageCapture shot;
  bool shot_is_set;
  /// The source describes general information about the camera source the image data was collected from.
  bosdyn_msgs__msg__ImageSource source;
  bool source_is_set;
  /// Return status of the request.
  bosdyn_msgs__msg__ImageResponseStatus status;
  /// Previous fields in the protobuf that are now reserved.
  /// Filled out if status is STATUS_CUSTOM_PARAMS_ERROR.
  bosdyn_msgs__msg__CustomParamError custom_param_error;
  bool custom_param_error_is_set;
} bosdyn_msgs__msg__ImageResponse;

// Struct for a sequence of bosdyn_msgs__msg__ImageResponse.
typedef struct bosdyn_msgs__msg__ImageResponse__Sequence
{
  bosdyn_msgs__msg__ImageResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ImageResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__IMAGE_RESPONSE__STRUCT_H_
