// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ImageCapture.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__IMAGE_CAPTURE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__IMAGE_CAPTURE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'acquisition_time'
#include "builtin_interfaces/msg/detail/time__struct.h"
// Member 'transforms_snapshot'
#include "bosdyn_msgs/msg/detail/frame_tree_snapshot__struct.h"
// Member 'frame_name_image_sensor'
#include "rosidl_runtime_c/string.h"
// Member 'image'
#include "bosdyn_msgs/msg/detail/image__struct.h"
// Member 'capture_params'
#include "bosdyn_msgs/msg/detail/capture_parameters__struct.h"

/// Struct defined in msg/ImageCapture in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ImageCapture
{
  /// Rectangular color/greyscale images.
  /// The time at which the image data was acquired in the robot's time basis.
  builtin_interfaces__msg__Time acquisition_time;
  bool acquisition_time_is_set;
  /// A tree-based collection of transformations, which will include the transformations to each image's
  /// sensor in addition to transformations to the common frames ("vision", "body", "odom").
  /// All transforms within the snapshot are at the acquistion time of the image.
  bosdyn_msgs__msg__FrameTreeSnapshot transforms_snapshot;
  bool transforms_snapshot_is_set;
  /// The frame name for the image's sensor source. This will be included in the transform snapshot.
  rosidl_runtime_c__String frame_name_image_sensor;
  /// Image data.
  bosdyn_msgs__msg__Image image;
  bool image_is_set;
  /// Sensor parameters associated with this image capture.
  bosdyn_msgs__msg__CaptureParameters capture_params;
  bool capture_params_is_set;
} bosdyn_msgs__msg__ImageCapture;

// Struct for a sequence of bosdyn_msgs__msg__ImageCapture.
typedef struct bosdyn_msgs__msg__ImageCapture__Sequence
{
  bosdyn_msgs__msg__ImageCapture * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ImageCapture__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__IMAGE_CAPTURE__STRUCT_H_
