// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ImageSourceOneOfCameraModels.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__IMAGE_SOURCE_ONE_OF_CAMERA_MODELS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__IMAGE_SOURCE_ONE_OF_CAMERA_MODELS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'CAMERA_MODELS_NOT_SET'.
enum
{
  bosdyn_msgs__msg__ImageSourceOneOfCameraModels__CAMERA_MODELS_NOT_SET = 0
};

/// Constant 'CAMERA_MODELS_PINHOLE_SET'.
enum
{
  bosdyn_msgs__msg__ImageSourceOneOfCameraModels__CAMERA_MODELS_PINHOLE_SET = 1
};

// Include directives for member types
// Member 'pinhole'
#include "bosdyn_msgs/msg/detail/image_source_pinhole_model__struct.h"

/// Struct defined in msg/ImageSourceOneOfCameraModels in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ImageSourceOneOfCameraModels
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// Rectilinear camera model.
  bosdyn_msgs__msg__ImageSourcePinholeModel pinhole;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t camera_models_choice;
} bosdyn_msgs__msg__ImageSourceOneOfCameraModels;

// Struct for a sequence of bosdyn_msgs__msg__ImageSourceOneOfCameraModels.
typedef struct bosdyn_msgs__msg__ImageSourceOneOfCameraModels__Sequence
{
  bosdyn_msgs__msg__ImageSourceOneOfCameraModels * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ImageSourceOneOfCameraModels__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__IMAGE_SOURCE_ONE_OF_CAMERA_MODELS__STRUCT_H_
