// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/Int64ParamSpec.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__INT64_PARAM_SPEC__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__INT64_PARAM_SPEC__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'units'
#include "bosdyn_msgs/msg/detail/units__struct.h"

/// Struct defined in msg/Int64ParamSpec in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__Int64ParamSpec
{
  /// Default value. If unspecified, UIs can pick their own default OR force user to make a
  /// selection.
  int64_t default_value;
  bool default_value_is_set;
  /// Units of value, default_value, min_value, min_value.
  bosdyn_msgs__msg__Units units;
  bool units_is_set;
  /// A value sent by the client must be within this minimum and maximum (inclusive).
  /// If unset, only limited by system representation.
  /// ERROR: It is an error to specify a min_value larger than the max_value.
  ///
  /// ADVICE: If a client sends a value outside these bounds, reject, rather than clamp it.
  int64_t min_value;
  bool min_value_is_set;
  int64_t max_value;
  bool max_value_is_set;
} bosdyn_msgs__msg__Int64ParamSpec;

// Struct for a sequence of bosdyn_msgs__msg__Int64ParamSpec.
typedef struct bosdyn_msgs__msg__Int64ParamSpec__Sequence
{
  bosdyn_msgs__msg__Int64ParamSpec * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__Int64ParamSpec__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__INT64_PARAM_SPEC__STRUCT_H_
