// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/IREnableDisableRequestRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__IR_ENABLE_DISABLE_REQUEST_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__IR_ENABLE_DISABLE_REQUEST_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'REQUEST_UNKNOWN'.
/**
  * Unspecified value -- should not be used.
 */
enum
{
  bosdyn_msgs__msg__IREnableDisableRequestRequest__REQUEST_UNKNOWN = 0
};

/// Constant 'REQUEST_OFF'.
/**
  * Disable emissions.
 */
enum
{
  bosdyn_msgs__msg__IREnableDisableRequestRequest__REQUEST_OFF = 1
};

/// Constant 'REQUEST_ON'.
/**
  * Enable emissions.
 */
enum
{
  bosdyn_msgs__msg__IREnableDisableRequestRequest__REQUEST_ON = 2
};

/// Struct defined in msg/IREnableDisableRequestRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__IREnableDisableRequestRequest
{
  int8_t value;
} bosdyn_msgs__msg__IREnableDisableRequestRequest;

// Struct for a sequence of bosdyn_msgs__msg__IREnableDisableRequestRequest.
typedef struct bosdyn_msgs__msg__IREnableDisableRequestRequest__Sequence
{
  bosdyn_msgs__msg__IREnableDisableRequestRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__IREnableDisableRequestRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__IR_ENABLE_DISABLE_REQUEST_REQUEST__STRUCT_H_
