// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/LicenseInfo.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__LICENSE_INFO__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__LICENSE_INFO__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'status'
#include "bosdyn_msgs/msg/detail/license_info_status__struct.h"
// Member 'id'
// Member 'robot_serial'
// Member 'licensed_features'
#include "rosidl_runtime_c/string.h"
// Member 'not_valid_before'
// Member 'not_valid_after'
#include "builtin_interfaces/msg/detail/time__struct.h"

/// Struct defined in msg/LicenseInfo in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__LicenseInfo
{
  /// The status of the uploaded license for this robot.
  bosdyn_msgs__msg__LicenseInfoStatus status;
  /// Unique license number.
  rosidl_runtime_c__String id;
  /// Serial number of the robot this license covers.
  rosidl_runtime_c__String robot_serial;
  /// The license is not valid for use for any dates before this timestamp.
  builtin_interfaces__msg__Time not_valid_before;
  bool not_valid_before_is_set;
  /// The license is not valid for use for any dates after this timestamp.
  builtin_interfaces__msg__Time not_valid_after;
  bool not_valid_after_is_set;
  /// / Human readable list of licensed features included for this license.
  rosidl_runtime_c__String__Sequence licensed_features;
} bosdyn_msgs__msg__LicenseInfo;

// Struct for a sequence of bosdyn_msgs__msg__LicenseInfo.
typedef struct bosdyn_msgs__msg__LicenseInfo__Sequence
{
  bosdyn_msgs__msg__LicenseInfo * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__LicenseInfo__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__LICENSE_INFO__STRUCT_H_
