// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/LicenseInfoStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__LICENSE_INFO_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__LICENSE_INFO_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_VALID'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_VALID = 1
};

/// Constant 'STATUS_EXPIRED'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_EXPIRED = 2
};

/// Constant 'STATUS_NOT_YET_VALID'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_NOT_YET_VALID = 3
};

/// Constant 'STATUS_MALFORMED'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_MALFORMED = 4
};

/// Constant 'STATUS_SERIAL_MISMATCH'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_SERIAL_MISMATCH = 5
};

/// Constant 'STATUS_NO_LICENSE'.
enum
{
  bosdyn_msgs__msg__LicenseInfoStatus__STATUS_NO_LICENSE = 6
};

/// Struct defined in msg/LicenseInfoStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__LicenseInfoStatus
{
  int8_t value;
} bosdyn_msgs__msg__LicenseInfoStatus;

// Struct for a sequence of bosdyn_msgs__msg__LicenseInfoStatus.
typedef struct bosdyn_msgs__msg__LicenseInfoStatus__Sequence
{
  bosdyn_msgs__msg__LicenseInfoStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__LicenseInfoStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__LICENSE_INFO_STATUS__STRUCT_H_
