// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ListServiceEntriesResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__LIST_SERVICE_ENTRIES_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__LIST_SERVICE_ENTRIES_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'service_entries'
#include "bosdyn_msgs/msg/detail/service_entry__struct.h"

/// Struct defined in msg/ListServiceEntriesResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ListServiceEntriesResponse
{
  /// The ListServiceEntries response message returns all known services at the time the request
  /// was recieved.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// The resources managed by the LeaseService.
  bosdyn_msgs__msg__ServiceEntry__Sequence service_entries;
} bosdyn_msgs__msg__ListServiceEntriesResponse;

// Struct for a sequence of bosdyn_msgs__msg__ListServiceEntriesResponse.
typedef struct bosdyn_msgs__msg__ListServiceEntriesResponse__Sequence
{
  bosdyn_msgs__msg__ListServiceEntriesResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ListServiceEntriesResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__LIST_SERVICE_ENTRIES_RESPONSE__STRUCT_H_
