// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/LogStatusStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__LOG_STATUS_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__LOG_STATUS_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * The status was not set, so something went wrong.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_RECEIVED'.
/**
  * Request received, thread is not created for bundling the logs.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_RECEIVED = 1
};

/// Constant 'STATUS_IN_PROGRESS'.
/**
  * Request in progress, thread is actively creating the bundle.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_IN_PROGRESS = 2
};

/// Constant 'STATUS_SYNCING'.
/**
  * Log end_time has passed, server post processing taking place.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_SYNCING = 3
};

/// Constant 'STATUS_DONE'.
/**
  * Bundling process is complete with no failures and was terminated by API.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_DONE = 4
};

/// Constant 'STATUS_FAILED'.
/**
  * Failure encountered while generating bundle.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_FAILED = 5
};

/// Constant 'STATUS_TERMINATED'.
/**
  * Bundle creation was terminated by API prior to completion.
 */
enum
{
  bosdyn_msgs__msg__LogStatusStatus__STATUS_TERMINATED = 6
};

/// Struct defined in msg/LogStatusStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__LogStatusStatus
{
  int8_t value;
} bosdyn_msgs__msg__LogStatusStatus;

// Struct for a sequence of bosdyn_msgs__msg__LogStatusStatus.
typedef struct bosdyn_msgs__msg__LogStatusStatus__Sequence
{
  bosdyn_msgs__msg__LogStatusStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__LogStatusStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__LOG_STATUS_STATUS__STRUCT_H_
