// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/LogStatusType.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__LOG_STATUS_TYPE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__LOG_STATUS_TYPE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'TYPE_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__LogStatusType__TYPE_UNKNOWN = 0
};

/// Constant 'TYPE_EXPERIMENT'.
/**
  * A log into the future.
 */
enum
{
  bosdyn_msgs__msg__LogStatusType__TYPE_EXPERIMENT = 1
};

/// Constant 'TYPE_RETRO'.
/**
  * A retroactive log.
 */
enum
{
  bosdyn_msgs__msg__LogStatusType__TYPE_RETRO = 2
};

/// Struct defined in msg/LogStatusType in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__LogStatusType
{
  int8_t value;
} bosdyn_msgs__msg__LogStatusType;

// Struct for a sequence of bosdyn_msgs__msg__LogStatusType.
typedef struct bosdyn_msgs__msg__LogStatusType__Sequence
{
  bosdyn_msgs__msg__LogStatusType * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__LogStatusType__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__LOG_STATUS_TYPE__STRUCT_H_
