// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ManipulatorStateCarryState.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__MANIPULATOR_STATE_CARRY_STATE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__MANIPULATOR_STATE_CARRY_STATE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'CARRY_STATE_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__ManipulatorStateCarryState__CARRY_STATE_UNKNOWN = 0
};

/// Constant 'CARRY_STATE_NOT_CARRIABLE'.
enum
{
  bosdyn_msgs__msg__ManipulatorStateCarryState__CARRY_STATE_NOT_CARRIABLE = 1
};

/// Constant 'CARRY_STATE_CARRIABLE'.
enum
{
  bosdyn_msgs__msg__ManipulatorStateCarryState__CARRY_STATE_CARRIABLE = 2
};

/// Constant 'CARRY_STATE_CARRIABLE_AND_STOWABLE'.
enum
{
  bosdyn_msgs__msg__ManipulatorStateCarryState__CARRY_STATE_CARRIABLE_AND_STOWABLE = 3
};

/// Struct defined in msg/ManipulatorStateCarryState in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ManipulatorStateCarryState
{
  int8_t value;
} bosdyn_msgs__msg__ManipulatorStateCarryState;

// Struct for a sequence of bosdyn_msgs__msg__ManipulatorStateCarryState.
typedef struct bosdyn_msgs__msg__ManipulatorStateCarryState__Sequence
{
  bosdyn_msgs__msg__ManipulatorStateCarryState * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ManipulatorStateCarryState__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__MANIPULATOR_STATE_CARRY_STATE__STRUCT_H_
