// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ModelLabels.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__MODEL_LABELS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__MODEL_LABELS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'model_name'
// Member 'available_labels'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/ModelLabels in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ModelLabels
{
  /// Model name.
  rosidl_runtime_c__String model_name;
  /// List of class labels returned by this model.
  rosidl_runtime_c__String__Sequence available_labels;
} bosdyn_msgs__msg__ModelLabels;

// Struct for a sequence of bosdyn_msgs__msg__ModelLabels.
typedef struct bosdyn_msgs__msg__ModelLabels__Sequence
{
  bosdyn_msgs__msg__ModelLabels * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ModelLabels__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__MODEL_LABELS__STRUCT_H_
