// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ModifyPolicyResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__MODIFY_POLICY_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__MODIFY_POLICY_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/modify_policy_response_status__struct.h"
// Member 'added_policy'
// Member 'removed_policies'
#include "bosdyn_msgs/msg/detail/live_policy__struct.h"

/// Struct defined in msg/ModifyPolicyResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ModifyPolicyResponse
{
  /// If the Policy in the request was invalid, CODE_INVALID_REQUEST will be set in this header.
  /// In that case, no policies will have been removed.
  /// CODE_INVALID_REQUEST can also happen if the Policy contains unknown fields. This may happen
  /// if there is a version mismatch between client and server.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  bosdyn_msgs__msg__ModifyPolicyResponseStatus status;
  /// The policy added to the session, if any.
  bosdyn_msgs__msg__LivePolicy added_policy;
  bool added_policy_is_set;
  /// The policies removed from the session, if any.
  bosdyn_msgs__msg__LivePolicy__Sequence removed_policies;
} bosdyn_msgs__msg__ModifyPolicyResponse;

// Struct for a sequence of bosdyn_msgs__msg__ModifyPolicyResponse.
typedef struct bosdyn_msgs__msg__ModifyPolicyResponse__Sequence
{
  bosdyn_msgs__msg__ModifyPolicyResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ModifyPolicyResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__MODIFY_POLICY_RESPONSE__STRUCT_H_
