// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NamedArmPositionsCommandFeedback.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NAMED_ARM_POSITIONS_COMMAND_FEEDBACK__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NAMED_ARM_POSITIONS_COMMAND_FEEDBACK__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'status'
#include "bosdyn_msgs/msg/detail/named_arm_positions_command_feedback_status__struct.h"

/// Struct defined in msg/NamedArmPositionsCommandFeedback in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NamedArmPositionsCommandFeedback
{
  /// Current status of the request.
  bosdyn_msgs__msg__NamedArmPositionsCommandFeedbackStatus status;
} bosdyn_msgs__msg__NamedArmPositionsCommandFeedback;

// Struct for a sequence of bosdyn_msgs__msg__NamedArmPositionsCommandFeedback.
typedef struct bosdyn_msgs__msg__NamedArmPositionsCommandFeedback__Sequence
{
  bosdyn_msgs__msg__NamedArmPositionsCommandFeedback * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NamedArmPositionsCommandFeedback__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NAMED_ARM_POSITIONS_COMMAND_FEEDBACK__STRUCT_H_
