// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_AREA_CALLBACK_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_AREA_CALLBACK_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_NAVIGATING'.
/**
  * The robot is navigating the Area Callback region
 */
enum
{
  bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus__STATUS_NAVIGATING = 1
};

/// Constant 'STATUS_WAITING'.
/**
  * The robot is waiting for assistance to navigate through the Area Callback region
 */
enum
{
  bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus__STATUS_WAITING = 2
};

/// Constant 'STATUS_CALLBACK_IN_CONTROL'.
/**
  * The Area Callback service is in control of the robot
 */
enum
{
  bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus__STATUS_CALLBACK_IN_CONTROL = 3
};

/// Struct defined in msg/NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus
{
  int8_t value;
} bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus;

// Struct for a sequence of bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus.
typedef struct bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus__Sequence
{
  bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_AREA_CALLBACK_STATUS__STRUCT_H_
