// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NavigateToResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NAVIGATE_TO_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NAVIGATE_TO_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * An unknown / unexpected error occurred.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Request was accepted.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_NO_TIMESYNC'.
/**
  * Client has not done timesync with robot.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_NO_TIMESYNC = 2
};

/// Constant 'STATUS_EXPIRED'.
/**
  * The command was received after its end time had already passed.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_EXPIRED = 3
};

/// Constant 'STATUS_TOO_DISTANT'.
/**
  * The command end time was too far in the future.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_TOO_DISTANT = 4
};

/// Constant 'STATUS_ROBOT_IMPAIRED'.
/**
  * Cannot navigate a route if the robot has a critical
  *  perception fault, or behavior fault, or LIDAR not working.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_ROBOT_IMPAIRED = 5
};

/// Constant 'STATUS_RECORDING'.
/**
  * Cannot navigate a route while recording a map.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_RECORDING = 6
};

/// Constant 'STATUS_UNKNOWN_WAYPOINT'.
/**
  * One or more of the waypoints specified weren't in the map.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_UNKNOWN_WAYPOINT = 7
};

/// Constant 'STATUS_NO_PATH'.
/**
  * There is no path to the specified waypoint.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_NO_PATH = 8
};

/// Constant 'STATUS_FEATURE_DESERT'.
/**
  * Route contained too many waypoints with low-quality features.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_FEATURE_DESERT = 9
};

/// Constant 'STATUS_LOST'.
/**
  * Happens when you try to issue a navigate to while the robot is lost.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_LOST = 10
};

/// Constant 'STATUS_NOT_LOCALIZED_TO_MAP'.
/**
  * Happens when the current localization doesn't refer to any waypoint in the map (possibly uninitialized localization).
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_NOT_LOCALIZED_TO_MAP = 11
};

/// Constant 'STATUS_COULD_NOT_UPDATE_ROUTE'.
/**
  * Happens when graph nav refuses to follow the route you specified.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_COULD_NOT_UPDATE_ROUTE = 12
};

/// Constant 'STATUS_STUCK'.
/**
  * Happens when you try to issue a navigate to while the robot is stuck. Navigate to a different
  * waypoint, or clear the route and try again.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_STUCK = 13
};

/// Constant 'STATUS_UNRECOGNIZED_COMMAND'.
/**
  * Happens when you try to continue a command that was either expired, or had an unrecognized id.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_UNRECOGNIZED_COMMAND = 14
};

/// Constant 'STATUS_AREA_CALLBACK_ERROR'.
/**
  * Happens when you try to navigate along a route and a needed callback is no longer available.
 */
enum
{
  bosdyn_msgs__msg__NavigateToResponseStatus__STATUS_AREA_CALLBACK_ERROR = 15
};

/// Struct defined in msg/NavigateToResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NavigateToResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__NavigateToResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__NavigateToResponseStatus.
typedef struct bosdyn_msgs__msg__NavigateToResponseStatus__Sequence
{
  bosdyn_msgs__msg__NavigateToResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NavigateToResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NAVIGATE_TO_RESPONSE_STATUS__STRUCT_H_
