// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NetworkComputeInputDataBridge.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_INPUT_DATA_BRIDGE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_INPUT_DATA_BRIDGE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'image_sources_and_services'
#include "bosdyn_msgs/msg/detail/image_source_and_service__struct.h"
// Member 'parameters'
#include "bosdyn_msgs/msg/detail/compute_parameters__struct.h"

/// Struct defined in msg/NetworkComputeInputDataBridge in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NetworkComputeInputDataBridge
{
  /// *
  ///   * The network compute bridge will receive this input data, and convert it to a
  ///   * [NetworkComputeInputDataWorker] before sending an RPC to the network compute bridge worker.
  ///   *
  ///  Image sources to collect a number of images from.  The ImageResponses
  ///  will populate the [images] field in [NetworkComputeInputDataWorker].
  bosdyn_msgs__msg__ImageSourceAndService__Sequence image_sources_and_services;
  bosdyn_msgs__msg__ComputeParameters parameters;
  bool parameters_is_set;
} bosdyn_msgs__msg__NetworkComputeInputDataBridge;

// Struct for a sequence of bosdyn_msgs__msg__NetworkComputeInputDataBridge.
typedef struct bosdyn_msgs__msg__NetworkComputeInputDataBridge__Sequence
{
  bosdyn_msgs__msg__NetworkComputeInputDataBridge * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NetworkComputeInputDataBridge__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_INPUT_DATA_BRIDGE__STRUCT_H_
