// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NetworkComputeServerConfiguration.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_SERVER_CONFIGURATION__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_SERVER_CONFIGURATION__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'service_name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/NetworkComputeServerConfiguration in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NetworkComputeServerConfiguration
{
  /// Service name in the robot's Directory for the worker that will process the request.
  rosidl_runtime_c__String service_name;
} bosdyn_msgs__msg__NetworkComputeServerConfiguration;

// Struct for a sequence of bosdyn_msgs__msg__NetworkComputeServerConfiguration.
typedef struct bosdyn_msgs__msg__NetworkComputeServerConfiguration__Sequence
{
  bosdyn_msgs__msg__NetworkComputeServerConfiguration * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NetworkComputeServerConfiguration__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_SERVER_CONFIGURATION__STRUCT_H_
