// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NetworkComputeStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'NETWORK_COMPUTE_STATUS_UNKNOWN'.
/**
  * Status is not specified.
 */
enum
{
  bosdyn_msgs__msg__NetworkComputeStatus__NETWORK_COMPUTE_STATUS_UNKNOWN = 0
};

/// Constant 'NETWORK_COMPUTE_STATUS_SUCCESS'.
/**
  * Succeeded.
 */
enum
{
  bosdyn_msgs__msg__NetworkComputeStatus__NETWORK_COMPUTE_STATUS_SUCCESS = 1
};

/// Constant 'NETWORK_COMPUTE_STATUS_EXTERNAL_SERVICE_NOT_FOUND'.
/**
  * External service not found in the robot's directory.
 */
enum
{
  bosdyn_msgs__msg__NetworkComputeStatus__NETWORK_COMPUTE_STATUS_EXTERNAL_SERVICE_NOT_FOUND = 2
};

/// Constant 'NETWORK_COMPUTE_STATUS_EXTERNAL_SERVER_ERROR'.
/**
  * The call to the external server did not succeed.
 */
enum
{
  bosdyn_msgs__msg__NetworkComputeStatus__NETWORK_COMPUTE_STATUS_EXTERNAL_SERVER_ERROR = 3
};

/// Constant 'NETWORK_COMPUTE_STATUS_ROTATION_ERROR'.
/**
  * The robot failed to rotate the image as requested.
 */
enum
{
  bosdyn_msgs__msg__NetworkComputeStatus__NETWORK_COMPUTE_STATUS_ROTATION_ERROR = 4
};

/// Constant 'NETWORK_COMPUTE_STATUS_CUSTOM_PARAMS_ERROR'.
/**
  * One or more keys or values in the input custom_params are unsupported by the service.
  * See the custom_param_error for details.
 */
enum
{
  bosdyn_msgs__msg__NetworkComputeStatus__NETWORK_COMPUTE_STATUS_CUSTOM_PARAMS_ERROR = 5
};

/// Struct defined in msg/NetworkComputeStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NetworkComputeStatus
{
  int8_t value;
} bosdyn_msgs__msg__NetworkComputeStatus;

// Struct for a sequence of bosdyn_msgs__msg__NetworkComputeStatus.
typedef struct bosdyn_msgs__msg__NetworkComputeStatus__Sequence
{
  bosdyn_msgs__msg__NetworkComputeStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NetworkComputeStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NETWORK_COMPUTE_STATUS__STRUCT_H_
