// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NodeIdentifier.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NODE_IDENTIFIER__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NODE_IDENTIFIER__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'user_data_id'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/NodeIdentifier in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NodeIdentifier
{
  /// Unique integer set by the mission service when loading a mission.
  int64_t node_id;
  /// Unique string set by the autowalk service when compiling a walk.
  rosidl_runtime_c__String user_data_id;
} bosdyn_msgs__msg__NodeIdentifier;

// Struct for a sequence of bosdyn_msgs__msg__NodeIdentifier.
typedef struct bosdyn_msgs__msg__NodeIdentifier__Sequence
{
  bosdyn_msgs__msg__NodeIdentifier * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NodeIdentifier__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NODE_IDENTIFIER__STRUCT_H_
