// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/NodeOneOfType.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__NODE_ONE_OF_TYPE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__NODE_ONE_OF_TYPE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'TYPE_NOT_SET'.
enum
{
  bosdyn_msgs__msg__NodeOneOfType__TYPE_NOT_SET = 0
};

/// Constant 'TYPE_IMPL_SET'.
enum
{
  bosdyn_msgs__msg__NodeOneOfType__TYPE_IMPL_SET = 1
};

/// Constant 'TYPE_NODE_REFERENCE_SET'.
enum
{
  bosdyn_msgs__msg__NodeOneOfType__TYPE_NODE_REFERENCE_SET = 2
};

// Include directives for member types
// Member 'node_reference'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/NodeOneOfType in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__NodeOneOfType
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// Implementation of this node. For example, this may be a Sequence.
  ///         google.protobuf.Any impl = 4;
  /// Unique identifier of another node. If this is filled out, rather than the "impl", then
  /// the referenced node will be used in place of this one.
  rosidl_runtime_c__String node_reference;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t type_choice;
} bosdyn_msgs__msg__NodeOneOfType;

// Struct for a sequence of bosdyn_msgs__msg__NodeOneOfType.
typedef struct bosdyn_msgs__msg__NodeOneOfType__Sequence
{
  bosdyn_msgs__msg__NodeOneOfType * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__NodeOneOfType__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__NODE_ONE_OF_TYPE__STRUCT_H_
