// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/OneOfParam.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'key'
#include "rosidl_runtime_c/string.h"
// Member 'values'
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_serialized_message__struct.h"

/// Struct defined in msg/OneOfParam in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__OneOfParam
{
  /// A selected param from one of several options.  Can be useful to specify parameters
  /// that have correlations.
  ///
  /// Example 1 - A camera that advertises an "exposure" parameter:
  ///      OneOf Option 1: Auto exposure [no additional parameters]
  ///      OneOf Option 2: Manual exposure [additonal exposure double parameter from 0 - 100 ms]
  ///
  /// Example 2 - A NCB worker that will alert if temperature outside a specified bound:
  ///      OneOf Option 1: No alert [no additional parameters]
  ///      OneOf Option 2: Alert if above max [addional max_temp parameter]
  ///      OneOf Option 3: Alert if below min [additional min_temp parameter]
  ///      OneOf Option 4: Alert if above max or below min [additional max_temp and min_temp
  ///      parameters]
  ///
  /// In the above examples, the service advertises a OneOf spec, the UI lets user PICK which child
  /// of the OneOf they want, and then the UI lets the user specify any child specific parameters.
  rosidl_runtime_c__String key;
  /// The values of the chosen spec will is guaraunteed to be at value[key].
  /// The values of the other specs might at value[that_specs_key], but no guarantees.
  /// Serialized bosdyn_msgs/KeyStringValueBosdynMsgsDictParam to break recursion
  bosdyn_msgs__msg__KeyStringValueBosdynMsgsSerializedMessage__Sequence values;
} bosdyn_msgs__msg__OneOfParam;

// Struct for a sequence of bosdyn_msgs__msg__OneOfParam.
typedef struct bosdyn_msgs__msg__OneOfParam__Sequence
{
  bosdyn_msgs__msg__OneOfParam * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__OneOfParam__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM__STRUCT_H_
