// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/OneOfParamChildSpec.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM_CHILD_SPEC__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM_CHILD_SPEC__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'spec'
#include "bosdyn_msgs/msg/detail/serialized_message__struct.h"
// Member 'ui_info'
#include "bosdyn_msgs/msg/detail/user_interface_info__struct.h"

/// Struct defined in msg/OneOfParamChildSpec in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__OneOfParamChildSpec
{
  /// Serialized bosdyn_msgs/DictParamSpec to break recursion
  bosdyn_msgs__msg__SerializedMessage spec;
  bool spec_is_set;
  bosdyn_msgs__msg__UserInterfaceInfo ui_info;
  bool ui_info_is_set;
} bosdyn_msgs__msg__OneOfParamChildSpec;

// Struct for a sequence of bosdyn_msgs__msg__OneOfParamChildSpec.
typedef struct bosdyn_msgs__msg__OneOfParamChildSpec__Sequence
{
  bosdyn_msgs__msg__OneOfParamChildSpec * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__OneOfParamChildSpec__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM_CHILD_SPEC__STRUCT_H_
