// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/OneOfParamSpec.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM_SPEC__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM_SPEC__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'specs'
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_one_of_param_child_spec__struct.h"
// Member 'default_key'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/OneOfParamSpec in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__OneOfParamSpec
{
  /// What options are available.  Only one will be specified by the user.
  ///
  /// If an option has no additional parameters, its spec should be an empty DictParam.Spec.
  bosdyn_msgs__msg__KeyStringValueBosdynMsgsOneOfParamChildSpec__Sequence specs;
  /// Which option to start selected.  If left blank, UI will pick one for you.
  rosidl_runtime_c__String default_key;
} bosdyn_msgs__msg__OneOfParamSpec;

// Struct for a sequence of bosdyn_msgs__msg__OneOfParamSpec.
typedef struct bosdyn_msgs__msg__OneOfParamSpec__Sequence
{
  bosdyn_msgs__msg__OneOfParamSpec * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__OneOfParamSpec__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ONE_OF_PARAM_SPEC__STRUCT_H_
