// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/PageInfoPageFormat.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__PAGE_INFO_PAGE_FORMAT__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__PAGE_INFO_PAGE_FORMAT__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'FORMAT_UNKNOWN'.
/**
  * Unset -- do not use.
 */
enum
{
  bosdyn_msgs__msg__PageInfoPageFormat__FORMAT_UNKNOWN = 0
};

/// Constant 'FORMAT_BDDF_FILE'.
/**
  * Data is stored in a .bddf file
 */
enum
{
  bosdyn_msgs__msg__PageInfoPageFormat__FORMAT_BDDF_FILE = 1
};

/// Struct defined in msg/PageInfoPageFormat in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__PageInfoPageFormat
{
  /// In the future, potentially support other file formats, database storage, etc....
  int8_t value;
} bosdyn_msgs__msg__PageInfoPageFormat;

// Struct for a sequence of bosdyn_msgs__msg__PageInfoPageFormat.
typedef struct bosdyn_msgs__msg__PageInfoPageFormat__Sequence
{
  bosdyn_msgs__msg__PageInfoPageFormat * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__PageInfoPageFormat__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__PAGE_INFO_PAGE_FORMAT__STRUCT_H_
