// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/PauseMissionResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__PAUSE_MISSION_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__PAUSE_MISSION_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * Invalid status, do not use.
 */
enum
{
  bosdyn_msgs__msg__PauseMissionResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Mission is paused or finished running.
 */
enum
{
  bosdyn_msgs__msg__PauseMissionResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_NO_MISSION_PLAYING'.
/**
  * No mission has started playing.
  * NOT returned when two PauseMissionRequests are received back-to-back. In that case,
  * you will get STATUS_OK.
 */
enum
{
  bosdyn_msgs__msg__PauseMissionResponseStatus__STATUS_NO_MISSION_PLAYING = 2
};

/// Struct defined in msg/PauseMissionResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__PauseMissionResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__PauseMissionResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__PauseMissionResponseStatus.
typedef struct bosdyn_msgs__msg__PauseMissionResponseStatus__Sequence
{
  bosdyn_msgs__msg__PauseMissionResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__PauseMissionResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__PAUSE_MISSION_RESPONSE_STATUS__STRUCT_H_
