// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/PointCloudResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'status'
#include "bosdyn_msgs/msg/detail/point_cloud_response_status__struct.h"
// Member 'point_cloud'
#include "bosdyn_msgs/msg/detail/point_cloud__struct.h"

/// Struct defined in msg/PointCloudResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__PointCloudResponse
{
  /// Return status for the request.
  bosdyn_msgs__msg__PointCloudResponseStatus status;
  /// The current point cloud from the service.
  bosdyn_msgs__msg__PointCloud point_cloud;
  bool point_cloud_is_set;
} bosdyn_msgs__msg__PointCloudResponse;

// Struct for a sequence of bosdyn_msgs__msg__PointCloudResponse.
typedef struct bosdyn_msgs__msg__PointCloudResponse__Sequence
{
  bosdyn_msgs__msg__PointCloudResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__PointCloudResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_RESPONSE__STRUCT_H_
