// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/PointCloudRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'point_cloud_source_name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/PointCloudRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__PointCloudRequest
{
  /// Name of the point cloud source to request from.
  rosidl_runtime_c__String point_cloud_source_name;
} bosdyn_msgs__msg__PointCloudRequest;

// Struct for a sequence of bosdyn_msgs__msg__PointCloudRequest.
typedef struct bosdyn_msgs__msg__PointCloudRequest__Sequence
{
  bosdyn_msgs__msg__PointCloudRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__PointCloudRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_REQUEST__STRUCT_H_
