// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/PointCloudResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * UNKNOWN should never be used.
  * An internal PointCloudService issue has happened if UNKNOWN is set.
  * None of the other fields are filled out.
 */
enum
{
  bosdyn_msgs__msg__PointCloudResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Call succeeded at filling out all the fields.
 */
enum
{
  bosdyn_msgs__msg__PointCloudResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_SOURCE_DATA_ERROR'.
/**
  * Failed to fill out PointCloudSource. All the other fields are not filled out.
 */
enum
{
  bosdyn_msgs__msg__PointCloudResponseStatus__STATUS_SOURCE_DATA_ERROR = 2
};

/// Constant 'STATUS_POINT_CLOUD_DATA_ERROR'.
/**
  * There was a problem with the point cloud data.  Only the PointCloudSource is filled out.
 */
enum
{
  bosdyn_msgs__msg__PointCloudResponseStatus__STATUS_POINT_CLOUD_DATA_ERROR = 3
};

/// Constant 'STATUS_UNKNOWN_SOURCE'.
/**
  * Provided point cloud source was not found. One
 */
enum
{
  bosdyn_msgs__msg__PointCloudResponseStatus__STATUS_UNKNOWN_SOURCE = 4
};

/// Struct defined in msg/PointCloudResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__PointCloudResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__PointCloudResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__PointCloudResponseStatus.
typedef struct bosdyn_msgs__msg__PointCloudResponseStatus__Sequence
{
  bosdyn_msgs__msg__PointCloudResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__PointCloudResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__POINT_CLOUD_RESPONSE_STATUS__STRUCT_H_
