// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/PtzFocusStatePtzFocusMode.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__PTZ_FOCUS_STATE_PTZ_FOCUS_MODE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__PTZ_FOCUS_STATE_PTZ_FOCUS_MODE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'PTZ_FOCUS_UNDEFINED'.
enum
{
  bosdyn_msgs__msg__PtzFocusStatePtzFocusMode__PTZ_FOCUS_UNDEFINED = 0
};

/// Constant 'PTZ_FOCUS_AUTO'.
enum
{
  bosdyn_msgs__msg__PtzFocusStatePtzFocusMode__PTZ_FOCUS_AUTO = 1
};

/// Constant 'PTZ_FOCUS_MANUAL'.
enum
{
  bosdyn_msgs__msg__PtzFocusStatePtzFocusMode__PTZ_FOCUS_MANUAL = 2
};

/// Struct defined in msg/PtzFocusStatePtzFocusMode in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__PtzFocusStatePtzFocusMode
{
  int8_t value;
} bosdyn_msgs__msg__PtzFocusStatePtzFocusMode;

// Struct for a sequence of bosdyn_msgs__msg__PtzFocusStatePtzFocusMode.
typedef struct bosdyn_msgs__msg__PtzFocusStatePtzFocusMode__Sequence
{
  bosdyn_msgs__msg__PtzFocusStatePtzFocusMode * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__PtzFocusStatePtzFocusMode__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__PTZ_FOCUS_STATE_PTZ_FOCUS_MODE__STRUCT_H_
