// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RayProperties.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__RAY_PROPERTIES__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__RAY_PROPERTIES__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'ray'
#include "bosdyn_msgs/msg/detail/ray__struct.h"
// Member 'frame'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/RayProperties in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RayProperties
{
  /// Ray, usually pointing from the camera to the object.
  bosdyn_msgs__msg__Ray ray;
  bool ray_is_set;
  /// Frame the ray is expressed with respect to.
  rosidl_runtime_c__String frame;
} bosdyn_msgs__msg__RayProperties;

// Struct for a sequence of bosdyn_msgs__msg__RayProperties.
typedef struct bosdyn_msgs__msg__RayProperties__Sequence
{
  bosdyn_msgs__msg__RayProperties * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RayProperties__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__RAY_PROPERTIES__STRUCT_H_
