// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RaycastResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__RAYCAST_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__RAYCAST_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * An unknown / unexpected error occurred.
 */
enum
{
  bosdyn_msgs__msg__RaycastResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Request was accepted.
 */
enum
{
  bosdyn_msgs__msg__RaycastResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_INVALID_REQUEST'.
/**
  * Request was invalid / malformed in some way.
 */
enum
{
  bosdyn_msgs__msg__RaycastResponseStatus__STATUS_INVALID_REQUEST = 2
};

/// Constant 'STATUS_INVALID_INTERSECTION_TYPE'.
/**
  * Requested source not valid for current robot configuration.
 */
enum
{
  bosdyn_msgs__msg__RaycastResponseStatus__STATUS_INVALID_INTERSECTION_TYPE = 3
};

/// Constant 'STATUS_UNKNOWN_FRAME'.
/**
  * The frame_name for a command was not a known frame.
 */
enum
{
  bosdyn_msgs__msg__RaycastResponseStatus__STATUS_UNKNOWN_FRAME = 4
};

/// Struct defined in msg/RaycastResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RaycastResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__RaycastResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__RaycastResponseStatus.
typedef struct bosdyn_msgs__msg__RaycastResponseStatus__Sequence
{
  bosdyn_msgs__msg__RaycastResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RaycastResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__RAYCAST_RESPONSE_STATUS__STRUCT_H_
