// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RecordOperatorCommentsRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__RECORD_OPERATOR_COMMENTS_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__RECORD_OPERATOR_COMMENTS_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'operator_comments'
#include "bosdyn_msgs/msg/detail/operator_comment__struct.h"

/// Struct defined in msg/RecordOperatorCommentsRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RecordOperatorCommentsRequest
{
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// The operator comments to be logged.
  bosdyn_msgs__msg__OperatorComment__Sequence operator_comments;
} bosdyn_msgs__msg__RecordOperatorCommentsRequest;

// Struct for a sequence of bosdyn_msgs__msg__RecordOperatorCommentsRequest.
typedef struct bosdyn_msgs__msg__RecordOperatorCommentsRequest__Sequence
{
  bosdyn_msgs__msg__RecordOperatorCommentsRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RecordOperatorCommentsRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__RECORD_OPERATOR_COMMENTS_REQUEST__STRUCT_H_
