// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RecordSignalTicksResponseError.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__RECORD_SIGNAL_TICKS_RESPONSE_ERROR__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__RECORD_SIGNAL_TICKS_RESPONSE_ERROR__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'type'
#include "bosdyn_msgs/msg/detail/record_signal_ticks_response_error_type__struct.h"
// Member 'message'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/RecordSignalTicksResponseError in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RecordSignalTicksResponseError
{
  /// The type of error: if it was caused by the client, the service, or something else.
  bosdyn_msgs__msg__RecordSignalTicksResponseErrorType type;
  /// An error message.
  rosidl_runtime_c__String message;
  /// The index to identify the data being stored.
  uint32_t index;
} bosdyn_msgs__msg__RecordSignalTicksResponseError;

// Struct for a sequence of bosdyn_msgs__msg__RecordSignalTicksResponseError.
typedef struct bosdyn_msgs__msg__RecordSignalTicksResponseError__Sequence
{
  bosdyn_msgs__msg__RecordSignalTicksResponseError * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RecordSignalTicksResponseError__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__RECORD_SIGNAL_TICKS_RESPONSE_ERROR__STRUCT_H_
