// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RecordDataBlobsRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__RECORD_DATA_BLOBS_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__RECORD_DATA_BLOBS_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'blob_data'
#include "bosdyn_msgs/msg/detail/data_blob__struct.h"

/// Struct defined in msg/RecordDataBlobsRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RecordDataBlobsRequest
{
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// The data blobs to be logged.
  bosdyn_msgs__msg__DataBlob__Sequence blob_data;
  /// When set, the data blob is committed to the log synchronously. The RPC does not return until
  /// the data is written.
  bool sync;
} bosdyn_msgs__msg__RecordDataBlobsRequest;

// Struct for a sequence of bosdyn_msgs__msg__RecordDataBlobsRequest.
typedef struct bosdyn_msgs__msg__RecordDataBlobsRequest__Sequence
{
  bosdyn_msgs__msg__RecordDataBlobsRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RecordDataBlobsRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__RECORD_DATA_BLOBS_REQUEST__STRUCT_H_
