// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RegisterEstopEndpointResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__REGISTER_ESTOP_ENDPOINT_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__REGISTER_ESTOP_ENDPOINT_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'request'
#include "bosdyn_msgs/msg/detail/register_estop_endpoint_request__struct.h"
// Member 'new_endpoint'
#include "bosdyn_msgs/msg/detail/estop_endpoint__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/register_estop_endpoint_response_status__struct.h"

/// Struct defined in msg/RegisterEstopEndpointResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RegisterEstopEndpointResponse
{
  /// Response to registration request.
  /// Common response header
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Copy of the initial request.
  bosdyn_msgs__msg__RegisterEstopEndpointRequest request;
  bool request_is_set;
  /// The resulting endpoint on success.
  bosdyn_msgs__msg__EstopEndpoint new_endpoint;
  bool new_endpoint_is_set;
  /// Status code for the response.
  bosdyn_msgs__msg__RegisterEstopEndpointResponseStatus status;
} bosdyn_msgs__msg__RegisterEstopEndpointResponse;

// Struct for a sequence of bosdyn_msgs__msg__RegisterEstopEndpointResponse.
typedef struct bosdyn_msgs__msg__RegisterEstopEndpointResponse__Sequence
{
  bosdyn_msgs__msg__RegisterEstopEndpointResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RegisterEstopEndpointResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__REGISTER_ESTOP_ENDPOINT_RESPONSE__STRUCT_H_
