// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RegionOfInterestParam.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__REGION_OF_INTEREST_PARAM__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__REGION_OF_INTEREST_PARAM__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'area'
#include "bosdyn_msgs/msg/detail/area_i__struct.h"
// Member 'service_and_source'
#include "bosdyn_msgs/msg/detail/region_of_interest_param_service_and_source__struct.h"

/// Struct defined in msg/RegionOfInterestParam in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RegionOfInterestParam
{
  /// Region of Interest parameter, region is associated with a specific image.
  bosdyn_msgs__msg__AreaI area;
  bool area_is_set;
  /// The name of the image service and source the UI had the user specify the ROI on.
  bosdyn_msgs__msg__RegionOfInterestParamServiceAndSource service_and_source;
  bool service_and_source_is_set;
  /// Width of the image (in pixels) when the ROI was specified.
  /// This should be used to ensure that the ROI is applied to an image with the same
  /// size / aspect ratio.
  int32_t image_cols;
  /// Height of the image (in pixels).
  /// This should be used to ensure that the ROI is applied to an image with the same
  /// size / aspect ratio.
  int32_t image_rows;
} bosdyn_msgs__msg__RegionOfInterestParam;

// Struct for a sequence of bosdyn_msgs__msg__RegionOfInterestParam.
typedef struct bosdyn_msgs__msg__RegionOfInterestParam__Sequence
{
  bosdyn_msgs__msg__RegionOfInterestParam * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RegionOfInterestParam__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__REGION_OF_INTEREST_PARAM__STRUCT_H_
