// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RobotCommandResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ROBOT_COMMAND_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ROBOT_COMMAND_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * An unknown / unexpected error occurred.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Request was accepted.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_INVALID_REQUEST'.
/**
  * Request was invalid / malformed in some way.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_INVALID_REQUEST = 2
};

/// Constant 'STATUS_UNSUPPORTED'.
/**
  * The robot does not understand this command.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_UNSUPPORTED = 3
};

/// Constant 'STATUS_NO_TIMESYNC'.
/**
  * Client has not done timesync with robot.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_NO_TIMESYNC = 4
};

/// Constant 'STATUS_EXPIRED'.
/**
  * The command was received after its end_time had already passed.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_EXPIRED = 5
};

/// Constant 'STATUS_TOO_DISTANT'.
/**
  * The command end time was too far in the future.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_TOO_DISTANT = 6
};

/// Constant 'STATUS_NOT_POWERED_ON'.
/**
  * The robot must be powered on to accept a command.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_NOT_POWERED_ON = 7
};

/// Constant 'STATUS_BEHAVIOR_FAULT'.
/**
  * The robot must not have behavior faults.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_BEHAVIOR_FAULT = 8
};

/// Constant 'STATUS_DOCKED'.
/**
  * The robot cannot be docked for certain commands.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_DOCKED = 9
};

/// Constant 'STATUS_UNKNOWN_FRAME'.
/**
  * The frame_name for a command was not a known frame.
 */
enum
{
  bosdyn_msgs__msg__RobotCommandResponseStatus__STATUS_UNKNOWN_FRAME = 10
};

/// Struct defined in msg/RobotCommandResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RobotCommandResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__RobotCommandResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__RobotCommandResponseStatus.
typedef struct bosdyn_msgs__msg__RobotCommandResponseStatus__Sequence
{
  bosdyn_msgs__msg__RobotCommandResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RobotCommandResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ROBOT_COMMAND_RESPONSE_STATUS__STRUCT_H_
