// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RobotLinkModelRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ROBOT_LINK_MODEL_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ROBOT_LINK_MODEL_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'link_name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/RobotLinkModelRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RobotLinkModelRequest
{
  /// The RobotLinkModel request message uses a link name returned by the RobotHardwareConfiguration response to
  /// get the associated OBJ file.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// The link name of which the OBJ file shoould represent.
  rosidl_runtime_c__String link_name;
} bosdyn_msgs__msg__RobotLinkModelRequest;

// Struct for a sequence of bosdyn_msgs__msg__RobotLinkModelRequest.
typedef struct bosdyn_msgs__msg__RobotLinkModelRequest__Sequence
{
  bosdyn_msgs__msg__RobotLinkModelRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RobotLinkModelRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ROBOT_LINK_MODEL_REQUEST__STRUCT_H_
