// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/RobotCommand.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ROBOT_COMMAND__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ROBOT_COMMAND__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'command'
#include "bosdyn_msgs/msg/detail/robot_command_one_of_command__struct.h"

/// Struct defined in msg/RobotCommand in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__RobotCommand
{
  /// A command for a robot to execute.
  /// The server decides if a set of commands is valid for a given robot and configuration.
  bosdyn_msgs__msg__RobotCommandOneOfCommand command;
} bosdyn_msgs__msg__RobotCommand;

// Struct for a sequence of bosdyn_msgs__msg__RobotCommand.
typedef struct bosdyn_msgs__msg__RobotCommand__Sequence
{
  bosdyn_msgs__msg__RobotCommand * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__RobotCommand__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ROBOT_COMMAND__STRUCT_H_
