// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/Route.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__ROUTE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__ROUTE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'waypoint_id'
#include "rosidl_runtime_c/string.h"
// Member 'edge_id'
#include "bosdyn_msgs/msg/detail/edge_id__struct.h"

/// Struct defined in msg/Route in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__Route
{
  /// Route that the robot should follow or is currently following.
  /// Ordered list of waypoints to traverse, starting from index 0.
  rosidl_runtime_c__String__Sequence waypoint_id;
  /// Ordered list of edges to traverse between those waypoints.
  bosdyn_msgs__msg__EdgeId__Sequence edge_id;
} bosdyn_msgs__msg__Route;

// Struct for a sequence of bosdyn_msgs__msg__Route.
typedef struct bosdyn_msgs__msg__Route__Sequence
{
  bosdyn_msgs__msg__Route * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__Route__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__ROUTE__STRUCT_H_
