// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ScreenDescription.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SCREEN_DESCRIPTION__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SCREEN_DESCRIPTION__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/ScreenDescription in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ScreenDescription
{
  /// A "Screen" represents a particular layout of camera images
  /// used by the video stream.
  /// Unique identifer for a screen.
  rosidl_runtime_c__String name;
} bosdyn_msgs__msg__ScreenDescription;

// Struct for a sequence of bosdyn_msgs__msg__ScreenDescription.
typedef struct bosdyn_msgs__msg__ScreenDescription__Sequence
{
  bosdyn_msgs__msg__ScreenDescription * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ScreenDescription__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SCREEN_DESCRIPTION__STRUCT_H_
