// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SelfRightCommand.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SELF_RIGHT_COMMAND__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SELF_RIGHT_COMMAND__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/SelfRightCommand in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SelfRightCommand
{
  uint8_t structure_needs_at_least_one_member;
} bosdyn_msgs__msg__SelfRightCommand;

// Struct for a sequence of bosdyn_msgs__msg__SelfRightCommand.
typedef struct bosdyn_msgs__msg__SelfRightCommand__Sequence
{
  bosdyn_msgs__msg__SelfRightCommand * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SelfRightCommand__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SELF_RIGHT_COMMAND__STRUCT_H_
