// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SensorCompatibilityStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SENSOR_COMPATIBILITY_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SENSOR_COMPATIBILITY_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/SensorCompatibilityStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SensorCompatibilityStatus
{
  /// Info on whether the robot's current sensor setup is compatible with the recorded data
  /// in the map.
  /// If true, the loaded map has LIDAR data in it.
  bool map_has_lidar_data;
  /// If true, the robot is currently configured to use LIDAR data.
  bool robot_configured_for_lidar;
} bosdyn_msgs__msg__SensorCompatibilityStatus;

// Struct for a sequence of bosdyn_msgs__msg__SensorCompatibilityStatus.
typedef struct bosdyn_msgs__msg__SensorCompatibilityStatus__Sequence
{
  bosdyn_msgs__msg__SensorCompatibilityStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SensorCompatibilityStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SENSOR_COMPATIBILITY_STATUS__STRUCT_H_
