// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SeriesBlockIndexBlockEntry.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SERIES_BLOCK_INDEX_BLOCK_ENTRY__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SERIES_BLOCK_INDEX_BLOCK_ENTRY__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'timestamp'
#include "builtin_interfaces/msg/detail/time__struct.h"
// Member 'additional_indexes'
#include "rosidl_runtime_c/primitives_sequence.h"

/// Struct defined in msg/SeriesBlockIndexBlockEntry in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SeriesBlockIndexBlockEntry
{
  /// The timestamp of data in this block.
  builtin_interfaces__msg__Time timestamp;
  bool timestamp_is_set;
  /// The offset of the data block from the start of the file.
  uint64_t file_offset;
  /// Values of the additional indexes for describing this block.
  rosidl_runtime_c__int64__Sequence additional_indexes;
} bosdyn_msgs__msg__SeriesBlockIndexBlockEntry;

// Struct for a sequence of bosdyn_msgs__msg__SeriesBlockIndexBlockEntry.
typedef struct bosdyn_msgs__msg__SeriesBlockIndexBlockEntry__Sequence
{
  bosdyn_msgs__msg__SeriesBlockIndexBlockEntry * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SeriesBlockIndexBlockEntry__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SERIES_BLOCK_INDEX_BLOCK_ENTRY__STRUCT_H_
