// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SetGraspOverride.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SET_GRASP_OVERRIDE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SET_GRASP_OVERRIDE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'service_name'
// Member 'host'
#include "rosidl_runtime_c/string.h"
// Member 'grasp_override_request'
#include "bosdyn_msgs/msg/detail/api_grasp_override_request__struct.h"

/// Struct defined in msg/SetGraspOverride in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SetGraspOverride
{
  /// Set grasp override and carry state override requests
  /// Name of the service to use.
  rosidl_runtime_c__String service_name;
  /// Host machine of the directory server that the gripper camera param service is registered
  /// with.
  rosidl_runtime_c__String host;
  bosdyn_msgs__msg__ApiGraspOverrideRequest grasp_override_request;
  bool grasp_override_request_is_set;
} bosdyn_msgs__msg__SetGraspOverride;

// Struct for a sequence of bosdyn_msgs__msg__SetGraspOverride.
typedef struct bosdyn_msgs__msg__SetGraspOverride__Sequence
{
  bosdyn_msgs__msg__SetGraspOverride * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SetGraspOverride__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SET_GRASP_OVERRIDE__STRUCT_H_
