// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SetPassphraseResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SET_PASSPHRASE_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SET_PASSPHRASE_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"

/// Struct defined in msg/SetPassphraseResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SetPassphraseResponse
{
  /// Response from setting the disk encryption.
  /// After setting the passphrase, please reboot the system to
  /// remount the encrypted filesystem layer.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
} bosdyn_msgs__msg__SetPassphraseResponse;

// Struct for a sequence of bosdyn_msgs__msg__SetPassphraseResponse.
typedef struct bosdyn_msgs__msg__SetPassphraseResponse__Sequence
{
  bosdyn_msgs__msg__SetPassphraseResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SetPassphraseResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SET_PASSPHRASE_RESPONSE__STRUCT_H_
