// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SetLocalizationResponseSuspectedAmbiguity.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SET_LOCALIZATION_RESPONSE_SUSPECTED_AMBIGUITY__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SET_LOCALIZATION_RESPONSE_SUSPECTED_AMBIGUITY__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'alternate_robot_tform_waypoint'
#include "geometry_msgs/msg/detail/pose__struct.h"

/// Struct defined in msg/SetLocalizationResponseSuspectedAmbiguity in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SetLocalizationResponseSuspectedAmbiguity
{
  /// Example of a potentially ambiguous localization near the
  /// result of the initialization.
  geometry_msgs__msg__Pose alternate_robot_tform_waypoint;
  bool alternate_robot_tform_waypoint_is_set;
} bosdyn_msgs__msg__SetLocalizationResponseSuspectedAmbiguity;

// Struct for a sequence of bosdyn_msgs__msg__SetLocalizationResponseSuspectedAmbiguity.
typedef struct bosdyn_msgs__msg__SetLocalizationResponseSuspectedAmbiguity__Sequence
{
  bosdyn_msgs__msg__SetLocalizationResponseSuspectedAmbiguity * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SetLocalizationResponseSuspectedAmbiguity__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SET_LOCALIZATION_RESPONSE_SUSPECTED_AMBIGUITY__STRUCT_H_
