// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SignalTickEncoding.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SIGNAL_TICK_ENCODING__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SIGNAL_TICK_ENCODING__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'ENCODING_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__SignalTickEncoding__ENCODING_UNKNOWN = 0
};

/// Constant 'ENCODING_RAW'.
/**
  * Bytes array is a concatination of little-endian machine representations of
  *  the variables from the SignalSchema, in order listed in that schema.
 */
enum
{
  bosdyn_msgs__msg__SignalTickEncoding__ENCODING_RAW = 1
};

/// Struct defined in msg/SignalTickEncoding in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SignalTickEncoding
{
  /// Could add GZIP_DELTA, GZIP, etc here
  int8_t value;
} bosdyn_msgs__msg__SignalTickEncoding;

// Struct for a sequence of bosdyn_msgs__msg__SignalTickEncoding.
typedef struct bosdyn_msgs__msg__SignalTickEncoding__Sequence
{
  bosdyn_msgs__msg__SignalTickEncoding * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SignalTickEncoding__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SIGNAL_TICK_ENCODING__STRUCT_H_
