// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/Sound.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SOUND__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SOUND__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/Sound in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__Sound
{
  /// Identifier for a playable sound.
  /// internally, sounds are stored in a flat table. This name is the
  /// identifier of a sound effect
  rosidl_runtime_c__String name;
} bosdyn_msgs__msg__Sound;

// Struct for a sequence of bosdyn_msgs__msg__Sound.
typedef struct bosdyn_msgs__msg__Sound__Sequence
{
  bosdyn_msgs__msg__Sound * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__Sound__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SOUND__STRUCT_H_
