// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SpotCamPtzAdjustParameters.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SPOT_CAM_PTZ_ADJUST_PARAMETERS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SPOT_CAM_PTZ_ADJUST_PARAMETERS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'localization_varname'
// Member 'waypoint_id'
#include "rosidl_runtime_c/string.h"
// Member 'waypoint_tform_body'
#include "geometry_msgs/msg/detail/pose__struct.h"

/// Struct defined in msg/SpotCamPtzAdjustParameters in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SpotCamPtzAdjustParameters
{
  /// Variable name to retrieve the graph nav state from.
  rosidl_runtime_c__String localization_varname;
  /// Waypoint ID where this PTZ configuration was originally set up.
  rosidl_runtime_c__String waypoint_id;
  /// Pose of body in waypoint frame at the time this PTZ configuration was originally set up.
  geometry_msgs__msg__Pose waypoint_tform_body;
  bool waypoint_tform_body_is_set;
} bosdyn_msgs__msg__SpotCamPtzAdjustParameters;

// Struct for a sequence of bosdyn_msgs__msg__SpotCamPtzAdjustParameters.
typedef struct bosdyn_msgs__msg__SpotCamPtzAdjustParameters__Sequence
{
  bosdyn_msgs__msg__SpotCamPtzAdjustParameters * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SpotCamPtzAdjustParameters__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SPOT_CAM_PTZ_ADJUST_PARAMETERS__STRUCT_H_
