// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SpotCheckCommandRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SPOT_CHECK_COMMAND_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SPOT_CHECK_COMMAND_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'lease'
#include "bosdyn_msgs/msg/detail/lease__struct.h"
// Member 'command'
#include "bosdyn_msgs/msg/detail/spot_check_command_request_command__struct.h"

/// Struct defined in msg/SpotCheckCommandRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SpotCheckCommandRequest
{
  /// Request for the SpotCheckCommand service.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// The Lease to show ownership of the robot. Lease required to issue any SpotCheck command.
  bosdyn_msgs__msg__Lease lease;
  bool lease_is_set;
  /// The describing what the spot check service should do.
  bosdyn_msgs__msg__SpotCheckCommandRequestCommand command;
} bosdyn_msgs__msg__SpotCheckCommandRequest;

// Struct for a sequence of bosdyn_msgs__msg__SpotCheckCommandRequest.
typedef struct bosdyn_msgs__msg__SpotCheckCommandRequest__Sequence
{
  bosdyn_msgs__msg__SpotCheckCommandRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SpotCheckCommandRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SPOT_CHECK_COMMAND_REQUEST__STRUCT_H_
