// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SpotCheckFeedbackResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SPOT_CHECK_FEEDBACK_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SPOT_CHECK_FEEDBACK_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'state'
#include "bosdyn_msgs/msg/detail/spot_check_feedback_response_state__struct.h"
// Member 'last_command'
#include "bosdyn_msgs/msg/detail/spot_check_command_request_command__struct.h"
// Member 'error'
#include "bosdyn_msgs/msg/detail/spot_check_feedback_response_error__struct.h"
// Member 'camera_results'
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_depth_plane_spot_check_result__struct.h"
// Member 'load_cell_results'
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_load_cell_spot_check_result__struct.h"
// Member 'kinematic_cal_results'
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_joint_kinematic_check_result__struct.h"
// Member 'payload_result'
#include "bosdyn_msgs/msg/detail/payload_check_result__struct.h"
// Member 'hip_range_of_motion_results'
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_hip_range_of_motion_result__struct.h"
// Member 'last_cal_timestamp'
#include "builtin_interfaces/msg/detail/time__struct.h"

/// Struct defined in msg/SpotCheckFeedbackResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SpotCheckFeedbackResponse
{
  /// Response for the SpotCheckFeedback service.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// The state of the spot check routine.
  bosdyn_msgs__msg__SpotCheckFeedbackResponseState state;
  /// The last command executed by Spotcheck. When SpotCheck is in state WAITING_FOR_COMMAND,
  /// the last command has completed.
  bosdyn_msgs__msg__SpotCheckCommandRequestCommand last_command;
  /// If SpotCheck experienced an error, specific error details reported here.
  /// This reflects an error in the routine.
  /// The specifics of the error for the SpotCheck service.
  bosdyn_msgs__msg__SpotCheckFeedbackResponseError error;
  /// Results from camera check.
  /// The key string is the location of the camera (e.g. frontright, frontleft, left, ...)
  bosdyn_msgs__msg__KeyStringValueBosdynMsgsDepthPlaneSpotCheckResult__Sequence camera_results;
  /// Results from load cell calibration.
  /// The key string is the location of the joint (e.g. fl.hxa, fl.hya, fl.kna, ...)
  bosdyn_msgs__msg__KeyStringValueBosdynMsgsLoadCellSpotCheckResult__Sequence load_cell_results;
  /// Results from output position sensor calibration.
  /// The key string is the location of the joint (e.g. fl.hx, fl.hy, fl.kn, ...)
  bosdyn_msgs__msg__KeyStringValueBosdynMsgsJointKinematicCheckResult__Sequence kinematic_cal_results;
  /// Result from the payload check
  bosdyn_msgs__msg__PayloadCheckResult payload_result;
  bool payload_result_is_set;
  /// Results of foot height validation.
  /// The key string is the name of the leg (e.g. fl, fr, hl, ...)
  /// DEPRECATED as of 2.3.  Will be removed in 4.0.  Field is no longer being populated.
  /// Results of leg pair validation.
  /// The key string is the name of the leg pair (e.g. fl-fr, fl-hl, ...)
  /// DEPRECATED as of 2.3.  Will be removed in 4.0. Field is no longer being populated.
  /// Results of the hip range of motion check
  /// The key string is the name of the leg (e.g. fl, fr, hl, ...)
  bosdyn_msgs__msg__KeyStringValueBosdynMsgsHipRangeOfMotionResult__Sequence hip_range_of_motion_results;
  /// The approximate progress of the spot check routine, range.
  float progress;
  /// Timestamp for the most up-to-date calibration
  builtin_interfaces__msg__Time last_cal_timestamp;
  bool last_cal_timestamp_is_set;
} bosdyn_msgs__msg__SpotCheckFeedbackResponse;

// Struct for a sequence of bosdyn_msgs__msg__SpotCheckFeedbackResponse.
typedef struct bosdyn_msgs__msg__SpotCheckFeedbackResponse__Sequence
{
  bosdyn_msgs__msg__SpotCheckFeedbackResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SpotCheckFeedbackResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SPOT_CHECK_FEEDBACK_RESPONSE__STRUCT_H_
