// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/StairTransform.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__STAIR_TRANSFORM__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__STAIR_TRANSFORM__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'frame_tform_stairs'
#include "geometry_msgs/msg/detail/pose__struct.h"
// Member 'frame_name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/StairTransform in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__StairTransform
{
  /// The staircase origin is the bottom-center of the first rise.
  /// X-axis is oriented pointing up the stairs.
  /// Y-axis is oriented to the left when facing up the stairs.
  /// Z-axis is oriented facing up (opposite gravity).
  geometry_msgs__msg__Pose frame_tform_stairs;
  bool frame_tform_stairs_is_set;
  rosidl_runtime_c__String frame_name;
} bosdyn_msgs__msg__StairTransform;

// Struct for a sequence of bosdyn_msgs__msg__StairTransform.
typedef struct bosdyn_msgs__msg__StairTransform__Sequence
{
  bosdyn_msgs__msg__StairTransform * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__StairTransform__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__STAIR_TRANSFORM__STRUCT_H_
