// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/StandCommandFeedbackStandingState.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__STAND_COMMAND_FEEDBACK_STANDING_STATE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__STAND_COMMAND_FEEDBACK_STANDING_STATE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STANDING_UNKNOWN'.
/**
  * STANDING_UNKNOWN should never be used. If used, an internal error has happened.
 */
enum
{
  bosdyn_msgs__msg__StandCommandFeedbackStandingState__STANDING_UNKNOWN = 0
};

/// Constant 'STANDING_CONTROLLED'.
/**
  * Robot is standing up and actively controlling its body so it may occasionally make
  * small body adjustments.
 */
enum
{
  bosdyn_msgs__msg__StandCommandFeedbackStandingState__STANDING_CONTROLLED = 1
};

/// Constant 'STANDING_FROZEN'.
/**
  * Robot is standing still with its body frozen in place so it should not move unless
  * commanded to. Motion sensitive tasks like laser scanning should be performed in this
  * state.
 */
enum
{
  bosdyn_msgs__msg__StandCommandFeedbackStandingState__STANDING_FROZEN = 2
};

/// Struct defined in msg/StandCommandFeedbackStandingState in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__StandCommandFeedbackStandingState
{
  int8_t value;
} bosdyn_msgs__msg__StandCommandFeedbackStandingState;

// Struct for a sequence of bosdyn_msgs__msg__StandCommandFeedbackStandingState.
typedef struct bosdyn_msgs__msg__StandCommandFeedbackStandingState__Sequence
{
  bosdyn_msgs__msg__StandCommandFeedbackStandingState * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__StandCommandFeedbackStandingState__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__STAND_COMMAND_FEEDBACK_STANDING_STATE__STRUCT_H_
