// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/StanceCommandFeedbackStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__STANCE_COMMAND_FEEDBACK_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__STANCE_COMMAND_FEEDBACK_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__StanceCommandFeedbackStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_STANCED'.
/**
  * Robot has finished moving feet and they are at the specified position
 */
enum
{
  bosdyn_msgs__msg__StanceCommandFeedbackStatus__STATUS_STANCED = 1
};

/// Constant 'STATUS_GOING_TO_STANCE'.
/**
  * Robot is in the process of moving feet to specified position
 */
enum
{
  bosdyn_msgs__msg__StanceCommandFeedbackStatus__STATUS_GOING_TO_STANCE = 2
};

/// Constant 'STATUS_TOO_FAR_AWAY'.
/**
  * Robot is not moving, the specified stance was too far away.
  * Hint: Try using SE2TrajectoryCommand to safely put the robot at the
  *       correct location first.
 */
enum
{
  bosdyn_msgs__msg__StanceCommandFeedbackStatus__STATUS_TOO_FAR_AWAY = 3
};

/// Struct defined in msg/StanceCommandFeedbackStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__StanceCommandFeedbackStatus
{
  int8_t value;
} bosdyn_msgs__msg__StanceCommandFeedbackStatus;

// Struct for a sequence of bosdyn_msgs__msg__StanceCommandFeedbackStatus.
typedef struct bosdyn_msgs__msg__StanceCommandFeedbackStatus__Sequence
{
  bosdyn_msgs__msg__StanceCommandFeedbackStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__StanceCommandFeedbackStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__STANCE_COMMAND_FEEDBACK_STATUS__STRUCT_H_
