// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/StateStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__STATE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__STATE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * Invalid status, do not use.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_FAILURE'.
/**
  * The mission has failed due to a node failure.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_FAILURE = 1
};

/// Constant 'STATUS_RUNNING'.
/**
  * The mission is still running.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_RUNNING = 2
};

/// Constant 'STATUS_SUCCESS'.
/**
  * The mission succeeded!
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_SUCCESS = 3
};

/// Constant 'STATUS_PAUSED'.
/**
  * Execution has been paused.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_PAUSED = 4
};

/// Constant 'STATUS_ERROR'.
/**
  * The mission service itself encountered an unexpected error, outside of a node failing.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_ERROR = 5
};

/// Constant 'STATUS_NONE'.
/**
  * No mission has been loaded.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_NONE = 6
};

/// Constant 'STATUS_STOPPED'.
/**
  * The mission was stopped before completion.
 */
enum
{
  bosdyn_msgs__msg__StateStatus__STATUS_STOPPED = 7
};

/// Struct defined in msg/StateStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__StateStatus
{
  int8_t value;
} bosdyn_msgs__msg__StateStatus;

// Struct for a sequence of bosdyn_msgs__msg__StateStatus.
typedef struct bosdyn_msgs__msg__StateStatus__Sequence
{
  bosdyn_msgs__msg__StateStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__StateStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__STATE_STATUS__STRUCT_H_
