// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/StoreMetadataOneOfData.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__STORE_METADATA_ONE_OF_DATA__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__STORE_METADATA_ONE_OF_DATA__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'DATA_NOT_SET'.
/**
  * JSON representation of metadata
  *         google.protobuf.Struct metadata_json = 7;
 */
enum
{
  bosdyn_msgs__msg__StoreMetadataOneOfData__DATA_NOT_SET = 0
};

/// Constant 'DATA_METADATA_NAME_SET'.
enum
{
  bosdyn_msgs__msg__StoreMetadataOneOfData__DATA_METADATA_NAME_SET = 1
};

/// Constant 'DATA_METADATA_JSON_SET'.
enum
{
  bosdyn_msgs__msg__StoreMetadataOneOfData__DATA_METADATA_JSON_SET = 2
};

// Include directives for member types
// Member 'metadata_name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/StoreMetadataOneOfData in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__StoreMetadataOneOfData
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// The name of the metadata object in the blackboard to be stored.
  /// The metadata object can be any protobuf message.
  rosidl_runtime_c__String metadata_name;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t data_choice;
} bosdyn_msgs__msg__StoreMetadataOneOfData;

// Struct for a sequence of bosdyn_msgs__msg__StoreMetadataOneOfData.
typedef struct bosdyn_msgs__msg__StoreMetadataOneOfData__Sequence
{
  bosdyn_msgs__msg__StoreMetadataOneOfData * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__StoreMetadataOneOfData__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__STORE_METADATA_ONE_OF_DATA__STRUCT_H_
