// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/StraightStaircaseLanding.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__STRAIGHT_STAIRCASE_LANDING__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__STRAIGHT_STAIRCASE_LANDING__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'stairs_tform_landing_center'
#include "geometry_msgs/msg/detail/pose__struct.h"

/// Struct defined in msg/StraightStaircaseLanding in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__StraightStaircaseLanding
{
  /// Pose of the landing's center relative to the stairs frame.
  geometry_msgs__msg__Pose stairs_tform_landing_center;
  bool stairs_tform_landing_center_is_set;
  /// The half-size of the box representing the landing in the x axis.
  double landing_extent_x;
  /// The half-size of the box representing the landing in the y axis.
  double landing_extent_y;
} bosdyn_msgs__msg__StraightStaircaseLanding;

// Struct for a sequence of bosdyn_msgs__msg__StraightStaircaseLanding.
typedef struct bosdyn_msgs__msg__StraightStaircaseLanding__Sequence
{
  bosdyn_msgs__msg__StraightStaircaseLanding * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__StraightStaircaseLanding__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__STRAIGHT_STAIRCASE_LANDING__STRUCT_H_
