// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/SynchronizedCommandFeedback.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__SYNCHRONIZED_COMMAND_FEEDBACK__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__SYNCHRONIZED_COMMAND_FEEDBACK__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'arm_command_feedback'
#include "bosdyn_msgs/msg/detail/arm_command_feedback__struct.h"
// Member 'mobility_command_feedback'
#include "bosdyn_msgs/msg/detail/mobility_command_feedback__struct.h"
// Member 'gripper_command_feedback'
#include "bosdyn_msgs/msg/detail/gripper_command_feedback__struct.h"

/// Struct defined in msg/SynchronizedCommandFeedback in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__SynchronizedCommandFeedback
{
  bosdyn_msgs__msg__ArmCommandFeedback arm_command_feedback;
  bool arm_command_feedback_is_set;
  bosdyn_msgs__msg__MobilityCommandFeedback mobility_command_feedback;
  bool mobility_command_feedback_is_set;
  bosdyn_msgs__msg__GripperCommandFeedback gripper_command_feedback;
  bool gripper_command_feedback_is_set;
} bosdyn_msgs__msg__SynchronizedCommandFeedback;

// Struct for a sequence of bosdyn_msgs__msg__SynchronizedCommandFeedback.
typedef struct bosdyn_msgs__msg__SynchronizedCommandFeedback__Sequence
{
  bosdyn_msgs__msg__SynchronizedCommandFeedback * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__SynchronizedCommandFeedback__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__SYNCHRONIZED_COMMAND_FEEDBACK__STRUCT_H_
