// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/TagRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__TAG_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__TAG_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'point'
#include "bosdyn_msgs/msg/detail/logpoint__struct.h"

/// Struct defined in msg/TagRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__TagRequest
{
  /// Add tag metadata to an existing log point.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// Logpoint to add metadata to. Name and tag are used.
  bosdyn_msgs__msg__Logpoint point;
  bool point_is_set;
} bosdyn_msgs__msg__TagRequest;

// Struct for a sequence of bosdyn_msgs__msg__TagRequest.
typedef struct bosdyn_msgs__msg__TagRequest__Sequence
{
  bosdyn_msgs__msg__TagRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__TagRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__TAG_REQUEST__STRUCT_H_
