// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/TargetRelocalize.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__TARGET_RELOCALIZE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__TARGET_RELOCALIZE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'set_localization_request'
#include "bosdyn_msgs/msg/detail/set_localization_request__struct.h"

/// Struct defined in msg/TargetRelocalize in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__TargetRelocalize
{
  /// Some SetLocalizationRequests require that waypoint snapshots contain full images.
  /// Make sure your client is downloading / storing / uploading full snapshots if you
  /// plan on using this feature in your client.
  bosdyn_msgs__msg__SetLocalizationRequest set_localization_request;
  bool set_localization_request_is_set;
} bosdyn_msgs__msg__TargetRelocalize;

// Struct for a sequence of bosdyn_msgs__msg__TargetRelocalize.
typedef struct bosdyn_msgs__msg__TargetRelocalize__Sequence
{
  bosdyn_msgs__msg__TargetRelocalize * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__TargetRelocalize__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__TARGET_RELOCALIZE__STRUCT_H_
