// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/UnregisterServiceResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__UNREGISTER_SERVICE_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__UNREGISTER_SERVICE_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/unregister_service_response_status__struct.h"

/// Struct defined in msg/UnregisterServiceResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__UnregisterServiceResponse
{
  /// The UnregisterService response message has information of whether the service was unregistered.
  /// Common response Header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Return status for the request.
  bosdyn_msgs__msg__UnregisterServiceResponseStatus status;
} bosdyn_msgs__msg__UnregisterServiceResponse;

// Struct for a sequence of bosdyn_msgs__msg__UnregisterServiceResponse.
typedef struct bosdyn_msgs__msg__UnregisterServiceResponse__Sequence
{
  bosdyn_msgs__msg__UnregisterServiceResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__UnregisterServiceResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__UNREGISTER_SERVICE_RESPONSE__STRUCT_H_
