// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/UpdateCallbackResponseNavPolicyOption.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__UPDATE_CALLBACK_RESPONSE_NAV_POLICY_OPTION__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__UPDATE_CALLBACK_RESPONSE_NAV_POLICY_OPTION__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'OPTION_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption__OPTION_UNKNOWN = 0
};

/// Constant 'OPTION_CONTINUE'.
/**
  * Continue past the waypoint. If not already stopped at it, do not stop.
 */
enum
{
  bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption__OPTION_CONTINUE = 1
};

/// Constant 'OPTION_STOP'.
/**
  * Stop at the waypoint.
 */
enum
{
  bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption__OPTION_STOP = 2
};

/// Constant 'OPTION_CONTROL'.
/**
  * Stop at the waypoint and transfer control to the callback.
 */
enum
{
  bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption__OPTION_CONTROL = 3
};

/// Struct defined in msg/UpdateCallbackResponseNavPolicyOption in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption
{
  int8_t value;
} bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption;

// Struct for a sequence of bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption.
typedef struct bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption__Sequence
{
  bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__UpdateCallbackResponseNavPolicyOption__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__UPDATE_CALLBACK_RESPONSE_NAV_POLICY_OPTION__STRUCT_H_
