// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/UpdatePayloadVersionResponseStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__UPDATE_PAYLOAD_VERSION_RESPONSE_STATUS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__UPDATE_PAYLOAD_VERSION_RESPONSE_STATUS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'STATUS_UNKNOWN'.
/**
  * UNKNOWN should never be used. An internal PayloadRegistrationService issue has happened
  * if UNKNOWN is set.
 */
enum
{
  bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus__STATUS_UNKNOWN = 0
};

/// Constant 'STATUS_OK'.
/**
  * Success.  The payload version has been updated.
 */
enum
{
  bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus__STATUS_OK = 1
};

/// Constant 'STATUS_DOES_NOT_EXIST'.
/**
  * UpdatePayload failed because a payload with this GUID does not yet exist.
 */
enum
{
  bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus__STATUS_DOES_NOT_EXIST = 2
};

/// Constant 'STATUS_INVALID_CREDENTIALS'.
/**
  * UpdatePayload failed because the paylod guid & secret do not match any registered
  * payloads.
 */
enum
{
  bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus__STATUS_INVALID_CREDENTIALS = 3
};

/// Struct defined in msg/UpdatePayloadVersionResponseStatus in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus
{
  int8_t value;
} bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus;

// Struct for a sequence of bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus.
typedef struct bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus__Sequence
{
  bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__UpdatePayloadVersionResponseStatus__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__UPDATE_PAYLOAD_VERSION_RESPONSE_STATUS__STRUCT_H_
