// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/UploadWaypointSnapshotResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__UPLOAD_WAYPOINT_SNAPSHOT_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__UPLOAD_WAYPOINT_SNAPSHOT_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'lease_use_result'
#include "bosdyn_msgs/msg/detail/lease_use_result__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/upload_waypoint_snapshot_response_status__struct.h"
// Member 'sensor_status'
#include "bosdyn_msgs/msg/detail/sensor_compatibility_status__struct.h"
// Member 'map_stats'
#include "bosdyn_msgs/msg/detail/map_stats__struct.h"

/// Struct defined in msg/UploadWaypointSnapshotResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__UploadWaypointSnapshotResponse
{
  /// One response for the entire WaypointSnapshot after all chunks have
  /// been concatenated and deserialized.
  /// Common response header.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Details about how the lease was used.
  bosdyn_msgs__msg__LeaseUseResult lease_use_result;
  bool lease_use_result_is_set;
  bosdyn_msgs__msg__UploadWaypointSnapshotResponseStatus status;
  bosdyn_msgs__msg__SensorCompatibilityStatus sensor_status;
  bool sensor_status_is_set;
  /// General map statistics after upload.
  bosdyn_msgs__msg__MapStats map_stats;
  bool map_stats_is_set;
} bosdyn_msgs__msg__UploadWaypointSnapshotResponse;

// Struct for a sequence of bosdyn_msgs__msg__UploadWaypointSnapshotResponse.
typedef struct bosdyn_msgs__msg__UploadWaypointSnapshotResponse__Sequence
{
  bosdyn_msgs__msg__UploadWaypointSnapshotResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__UploadWaypointSnapshotResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__UPLOAD_WAYPOINT_SNAPSHOT_RESPONSE__STRUCT_H_
