// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/UploadGraphRequest.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__UPLOAD_GRAPH_REQUEST__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__UPLOAD_GRAPH_REQUEST__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/request_header__struct.h"
// Member 'graph'
#include "bosdyn_msgs/msg/detail/graph__struct.h"
// Member 'lease'
#include "bosdyn_msgs/msg/detail/lease__struct.h"

/// Struct defined in msg/UploadGraphRequest in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__UploadGraphRequest
{
  /// Uploads a graph to the server. This graph will be appended to the graph that
  /// currently exists on the server.
  /// Common request header.
  bosdyn_msgs__msg__RequestHeader header;
  bool header_is_set;
  /// Structure of the graph containing waypoints and edges without
  /// underlying sensor data.
  bosdyn_msgs__msg__Graph graph;
  bool graph_is_set;
  /// The Lease to show ownership of graph-nav service.
  bosdyn_msgs__msg__Lease lease;
  bool lease_is_set;
  /// If this is true, generate an (overwrite the) anchoring on upload.
  bool generate_new_anchoring;
  /// If true, validation warnings will be treated as errors, and STATUS_INVALID_GRAPH will be returned. This is false by
  /// default.
  bool treat_validation_warnings_as_errors;
} bosdyn_msgs__msg__UploadGraphRequest;

// Struct for a sequence of bosdyn_msgs__msg__UploadGraphRequest.
typedef struct bosdyn_msgs__msg__UploadGraphRequest__Sequence
{
  bosdyn_msgs__msg__UploadGraphRequest * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__UploadGraphRequest__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__UPLOAD_GRAPH_REQUEST__STRUCT_H_
