// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/UserData.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__USER_DATA__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__USER_DATA__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'id'
#include "rosidl_runtime_c/string.h"
// Member 'bytestring'
#include "rosidl_runtime_c/primitives_sequence.h"

/// Struct defined in msg/UserData in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__UserData
{
  /// Data a user can associate with a node.
  /// Identifier. Enables matching the Node uploaded to the MissionService with the NodeInfo
  /// downloaded from the MissionService.
  rosidl_runtime_c__String id;
  /// Arbitrary data. We recommend keeping it small, to avoid bloating the size of the mission.
  rosidl_runtime_c__octet__Sequence bytestring;
} bosdyn_msgs__msg__UserData;

// Struct for a sequence of bosdyn_msgs__msg__UserData.
typedef struct bosdyn_msgs__msg__UserData__Sequence
{
  bosdyn_msgs__msg__UserData * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__UserData__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__USER_DATA__STRUCT_H_
