// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ValidateGraphResponse.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__VALIDATE_GRAPH_RESPONSE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__VALIDATE_GRAPH_RESPONSE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'header'
#include "bosdyn_msgs/msg/detail/response_header__struct.h"
// Member 'status'
#include "bosdyn_msgs/msg/detail/validate_graph_response_status__struct.h"
// Member 'sensor_status'
#include "bosdyn_msgs/msg/detail/sensor_compatibility_status__struct.h"
// Member 'area_callback_error'
#include "bosdyn_msgs/msg/detail/area_callback_service_error__struct.h"

/// Struct defined in msg/ValidateGraphResponse in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ValidateGraphResponse
{
  /// Report possible errors with the loaded map.
  bosdyn_msgs__msg__ResponseHeader header;
  bool header_is_set;
  /// Status of the currently loaded map.
  bosdyn_msgs__msg__ValidateGraphResponseStatus status;
  bosdyn_msgs__msg__SensorCompatibilityStatus sensor_status;
  bool sensor_status_is_set;
  /// Errors about Area Callbacks in the map.
  bosdyn_msgs__msg__AreaCallbackServiceError area_callback_error;
  bool area_callback_error_is_set;
} bosdyn_msgs__msg__ValidateGraphResponse;

// Struct for a sequence of bosdyn_msgs__msg__ValidateGraphResponse.
typedef struct bosdyn_msgs__msg__ValidateGraphResponse__Sequence
{
  bosdyn_msgs__msg__ValidateGraphResponse * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ValidateGraphResponse__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__VALIDATE_GRAPH_RESPONSE__STRUCT_H_
