// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/ValueOneOfSource.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__VALUE_ONE_OF_SOURCE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__VALUE_ONE_OF_SOURCE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'SOURCE_NOT_SET'.
enum
{
  bosdyn_msgs__msg__ValueOneOfSource__SOURCE_NOT_SET = 0
};

/// Constant 'SOURCE_CONSTANT_SET'.
enum
{
  bosdyn_msgs__msg__ValueOneOfSource__SOURCE_CONSTANT_SET = 1
};

/// Constant 'SOURCE_RUNTIME_VAR_SET'.
enum
{
  bosdyn_msgs__msg__ValueOneOfSource__SOURCE_RUNTIME_VAR_SET = 2
};

/// Constant 'SOURCE_PARAMETER_SET'.
enum
{
  bosdyn_msgs__msg__ValueOneOfSource__SOURCE_PARAMETER_SET = 3
};

// Include directives for member types
// Member 'constant'
#include "bosdyn_msgs/msg/detail/constant_value__struct.h"
// Member 'runtime_var'
// Member 'parameter'
#include "bosdyn_msgs/msg/detail/variable_declaration__struct.h"

/// Struct defined in msg/ValueOneOfSource in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__ValueOneOfSource
{
  /// ONEOF MESSAGE  Only one of the following can be set
  /// A constant value.
  bosdyn_msgs__msg__ConstantValue constant;
  /// Look up a variable provided at run-time.
  bosdyn_msgs__msg__VariableDeclaration runtime_var;
  /// Look up a Node Parameter.
  bosdyn_msgs__msg__VariableDeclaration parameter;
  /// Only one of the above can be filled in.  Use the enum to choose which.
  int8_t source_choice;
} bosdyn_msgs__msg__ValueOneOfSource;

// Struct for a sequence of bosdyn_msgs__msg__ValueOneOfSource.
typedef struct bosdyn_msgs__msg__ValueOneOfSource__Sequence
{
  bosdyn_msgs__msg__ValueOneOfSource * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__ValueOneOfSource__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__VALUE_ONE_OF_SOURCE__STRUCT_H_
