// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/VariableDeclaration.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__VARIABLE_DECLARATION__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__VARIABLE_DECLARATION__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'name'
#include "rosidl_runtime_c/string.h"
// Member 'type'
#include "bosdyn_msgs/msg/detail/variable_declaration_type__struct.h"

/// Struct defined in msg/VariableDeclaration in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__VariableDeclaration
{
  /// Declaration of a run-time or compile-time variable.
  /// Name of the variable, to be used as the key in KeyValue pairs.
  rosidl_runtime_c__String name;
  /// Supported types for blackboard or parameter values.
  /// Type that this variable is expected to have. Used to verify assignments and comparisons.
  bosdyn_msgs__msg__VariableDeclarationType type;
} bosdyn_msgs__msg__VariableDeclaration;

// Struct for a sequence of bosdyn_msgs__msg__VariableDeclaration.
typedef struct bosdyn_msgs__msg__VariableDeclaration__Sequence
{
  bosdyn_msgs__msg__VariableDeclaration * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__VariableDeclaration__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__VARIABLE_DECLARATION__STRUCT_H_
