// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/Vec2Value.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__VEC2_VALUE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__VEC2_VALUE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/Vec2Value in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__Vec2Value
{
  /// A 2D vector of doubles that uses wrapped values so we can tell which elements are set.
  double x;
  bool x_is_set;
  double y;
  bool y_is_set;
} bosdyn_msgs__msg__Vec2Value;

// Struct for a sequence of bosdyn_msgs__msg__Vec2Value.
typedef struct bosdyn_msgs__msg__Vec2Value__Sequence
{
  bosdyn_msgs__msg__Vec2Value * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__Vec2Value__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__VEC2_VALUE__STRUCT_H_
