// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/VisualRefinementOptions.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__VISUAL_REFINEMENT_OPTIONS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__VISUAL_REFINEMENT_OPTIONS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Struct defined in msg/VisualRefinementOptions in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__VisualRefinementOptions
{
  /// Whether to return a STATUS_VISUAL_ALIGNMENT_FAILED if refine_with_visual_features fails.
  bool verify_refinement_quality;
} bosdyn_msgs__msg__VisualRefinementOptions;

// Struct for a sequence of bosdyn_msgs__msg__VisualRefinementOptions.
typedef struct bosdyn_msgs__msg__VisualRefinementOptions__Sequence
{
  bosdyn_msgs__msg__VisualRefinementOptions * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__VisualRefinementOptions__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__VISUAL_REFINEMENT_OPTIONS__STRUCT_H_
