// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/WalkToObjectRayInWorld.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__WALK_TO_OBJECT_RAY_IN_WORLD__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__WALK_TO_OBJECT_RAY_IN_WORLD__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'ray_start_rt_frame'
// Member 'ray_end_rt_frame'
#include "geometry_msgs/msg/detail/vector3__struct.h"
// Member 'frame_name'
#include "rosidl_runtime_c/string.h"

/// Struct defined in msg/WalkToObjectRayInWorld in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__WalkToObjectRayInWorld
{
  /// Walks the robot up to an object.  Useful to prepare to grasp or manipulate something.
  /// Position of the start of the ray (see PickObjectRayInWorld for detailed comments.)
  geometry_msgs__msg__Vector3 ray_start_rt_frame;
  bool ray_start_rt_frame_is_set;
  /// Position of the end of the ray.
  geometry_msgs__msg__Vector3 ray_end_rt_frame;
  bool ray_end_rt_frame_is_set;
  /// Name of the frame that the above parameters are expressed in.
  rosidl_runtime_c__String frame_name;
  /// Optional offset distance for the robot to stand from the object's location.  The robot will
  /// walk forwards or backwards from where it is so that its center of mass is this distance from
  /// the object.
  /// If unset, we use a reasonable default value.
  float offset_distance;
  bool offset_distance_is_set;
} bosdyn_msgs__msg__WalkToObjectRayInWorld;

// Struct for a sequence of bosdyn_msgs__msg__WalkToObjectRayInWorld.
typedef struct bosdyn_msgs__msg__WalkToObjectRayInWorld__Sequence
{
  bosdyn_msgs__msg__WalkToObjectRayInWorld * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__WalkToObjectRayInWorld__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__WALK_TO_OBJECT_RAY_IN_WORLD__STRUCT_H_
