// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/WaypointWaypointSource.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__WAYPOINT_WAYPOINT_SOURCE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__WAYPOINT_WAYPOINT_SOURCE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'WAYPOINT_SOURCE_UNKNOWN'.
enum
{
  bosdyn_msgs__msg__WaypointWaypointSource__WAYPOINT_SOURCE_UNKNOWN = 0
};

/// Constant 'WAYPOINT_SOURCE_ROBOT_PATH'.
/**
  * Waypoints from the robot's location during recording.
 */
enum
{
  bosdyn_msgs__msg__WaypointWaypointSource__WAYPOINT_SOURCE_ROBOT_PATH = 1
};

/// Constant 'WAYPOINT_SOURCE_USER_REQUEST'.
/**
  * Waypoints with user-requested placement.
 */
enum
{
  bosdyn_msgs__msg__WaypointWaypointSource__WAYPOINT_SOURCE_USER_REQUEST = 2
};

/// Constant 'WAYPOINT_SOURCE_ALTERNATE_ROUTE_FINDING'.
/**
  * Waypoints that may help find alternate routes.
 */
enum
{
  bosdyn_msgs__msg__WaypointWaypointSource__WAYPOINT_SOURCE_ALTERNATE_ROUTE_FINDING = 3
};

/// Struct defined in msg/WaypointWaypointSource in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__WaypointWaypointSource
{
  int8_t value;
} bosdyn_msgs__msg__WaypointWaypointSource;

// Struct for a sequence of bosdyn_msgs__msg__WaypointWaypointSource.
typedef struct bosdyn_msgs__msg__WaypointWaypointSource__Sequence
{
  bosdyn_msgs__msg__WaypointWaypointSource * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__WaypointWaypointSource__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__WAYPOINT_WAYPOINT_SOURCE__STRUCT_H_
