// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/WaypointAnnotations.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__WAYPOINT_ANNOTATIONS__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__WAYPOINT_ANNOTATIONS__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

// Include directives for member types
// Member 'name'
#include "rosidl_runtime_c/string.h"
// Member 'creation_time'
#include "builtin_interfaces/msg/detail/time__struct.h"
// Member 'icp_variance'
#include "bosdyn_msgs/msg/detail/se3_covariance__struct.h"
// Member 'scan_match_region'
#include "bosdyn_msgs/msg/detail/waypoint_annotations_localize_region__struct.h"
// Member 'waypoint_source'
#include "bosdyn_msgs/msg/detail/waypoint_waypoint_source__struct.h"
// Member 'client_metadata'
#include "bosdyn_msgs/msg/detail/client_metadata__struct.h"
// Member 'loop_closure_settings'
#include "bosdyn_msgs/msg/detail/waypoint_annotations_loop_closure_settings__struct.h"

/// Struct defined in msg/WaypointAnnotations in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__WaypointAnnotations
{
  /// Human-friendly name of the waypoint. For example, "Kitchen Fridge"
  rosidl_runtime_c__String name;
  /// The time that the waypoint was created while recording a map.
  builtin_interfaces__msg__Time creation_time;
  bool creation_time_is_set;
  /// Estimate of the variance of ICP when performed at this waypoint, collected at record
  /// time.
  bosdyn_msgs__msg__SE3Covariance icp_variance;
  bool icp_variance_is_set;
  /// Options for how to localize to a waypoint (if at all).
  bosdyn_msgs__msg__WaypointAnnotationsLocalizeRegion scan_match_region;
  bool scan_match_region_is_set;
  /// How this waypoint was made.
  bosdyn_msgs__msg__WaypointWaypointSource waypoint_source;
  /// Information about the state of the client when this waypoint was created.
  bosdyn_msgs__msg__ClientMetadata client_metadata;
  bool client_metadata_is_set;
  /// This waypoint may have specific settings to help with loop closure. This
  /// Is useful for example when trying to ensure that a loop closure occurs at
  /// a particular intersection or near a dock.
  bosdyn_msgs__msg__WaypointAnnotationsLoopClosureSettings loop_closure_settings;
  bool loop_closure_settings_is_set;
} bosdyn_msgs__msg__WaypointAnnotations;

// Struct for a sequence of bosdyn_msgs__msg__WaypointAnnotations.
typedef struct bosdyn_msgs__msg__WaypointAnnotations__Sequence
{
  bosdyn_msgs__msg__WaypointAnnotations * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__WaypointAnnotations__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__WAYPOINT_ANNOTATIONS__STRUCT_H_
