// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/WiFiStateMode.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__WI_FI_STATE_MODE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__WI_FI_STATE_MODE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'MODE_UNKNOWN'.
/**
  * The robot's comms state is unknown, or no user requested mode.
 */
enum
{
  bosdyn_msgs__msg__WiFiStateMode__MODE_UNKNOWN = 0
};

/// Constant 'MODE_ACCESS_POINT'.
/**
  * The robot is acting as an access point.
 */
enum
{
  bosdyn_msgs__msg__WiFiStateMode__MODE_ACCESS_POINT = 1
};

/// Constant 'MODE_CLIENT'.
/**
  * The robot is connected to a network.
 */
enum
{
  bosdyn_msgs__msg__WiFiStateMode__MODE_CLIENT = 2
};

/// Struct defined in msg/WiFiStateMode in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__WiFiStateMode
{
  int8_t value;
} bosdyn_msgs__msg__WiFiStateMode;

// Struct for a sequence of bosdyn_msgs__msg__WiFiStateMode.
typedef struct bosdyn_msgs__msg__WiFiStateMode__Sequence
{
  bosdyn_msgs__msg__WiFiStateMode * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__WiFiStateMode__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__WI_FI_STATE_MODE__STRUCT_H_
