// generated from rosidl_generator_c/resource/idl__struct.h.em
// with input from bosdyn_msgs:msg/WifiDeviceType.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__DETAIL__WIFI_DEVICE_TYPE__STRUCT_H_
#define BOSDYN_MSGS__MSG__DETAIL__WIFI_DEVICE_TYPE__STRUCT_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>


// Constants defined in the message

/// Constant 'UNKNOWN'.
enum
{
  bosdyn_msgs__msg__WifiDeviceType__UNKNOWN = 0
};

/// Constant 'AP'.
enum
{
  bosdyn_msgs__msg__WifiDeviceType__AP = 1
};

/// Constant 'CLIENT'.
enum
{
  bosdyn_msgs__msg__WifiDeviceType__CLIENT = 2
};

/// Struct defined in msg/WifiDeviceType in the package bosdyn_msgs.
/**
  * AUTOMATICALLY GENERATED BY PROTO CONVERSION
 */
typedef struct bosdyn_msgs__msg__WifiDeviceType
{
  int8_t value;
} bosdyn_msgs__msg__WifiDeviceType;

// Struct for a sequence of bosdyn_msgs__msg__WifiDeviceType.
typedef struct bosdyn_msgs__msg__WifiDeviceType__Sequence
{
  bosdyn_msgs__msg__WifiDeviceType * data;
  /// The number of valid items in data
  size_t size;
  /// The number of allocated items in data
  size_t capacity;
} bosdyn_msgs__msg__WifiDeviceType__Sequence;

#ifdef __cplusplus
}
#endif

#endif  // BOSDYN_MSGS__MSG__DETAIL__WIFI_DEVICE_TYPE__STRUCT_H_
