message_mapping:
  bosdyn.api.Vec3: geometry_msgs/Vector3
  bosdyn.api.Quaternion: geometry_msgs/Quaternion
  bosdyn.api.SE3Pose: geometry_msgs/Pose
  bosdyn.api.SE3Velocity: geometry_msgs/Twist
  bosdyn.api.Wrench: geometry_msgs/Wrench
package_mapping:
  bosdyn.api: bosdyn_api_msgs
  bosdyn.api.docking: bosdyn_api_msgs
  bosdyn.api.gps: bosdyn_api_msgs
  bosdyn.api.auto_return: bosdyn_auto_return_api_msgs
python_imports:
  - bosdyn_api_msgs.msg
  - bosdyn_auto_return_api_msgs.msg
inline_python_imports:
  - bosdyn_api_msgs.conversions
  - bosdyn_auto_return_api_msgs.conversions
cpp_headers:
  - bosdyn_api_msgs/conversions.hpp
  - bosdyn_api_msgs/manual_conversions.hpp
  - bosdyn_auto_return_api_msgs/conversions.hpp
inline_cpp_namespaces:
  - bosdyn_api_msgs::conversions
  - bosdyn_auto_return_api_msgs::conversions
package_specifications:
  - bosdyn_api_msgs.specifications
  - bosdyn_auto_return_api_msgs.specifications
