// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/ArmCartesianCommandRequestOneOfJointConfiguration.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__ARM_CARTESIAN_COMMAND_REQUEST_ONE_OF_JOINT_CONFIGURATION_H_
#define BOSDYN_MSGS__MSG__ARM_CARTESIAN_COMMAND_REQUEST_ONE_OF_JOINT_CONFIGURATION_H_

#include "bosdyn_msgs/msg/detail/arm_cartesian_command_request_one_of_joint_configuration__struct.h"
#include "bosdyn_msgs/msg/detail/arm_cartesian_command_request_one_of_joint_configuration__functions.h"
#include "bosdyn_msgs/msg/detail/arm_cartesian_command_request_one_of_joint_configuration__type_support.h"

#endif  // BOSDYN_MSGS__MSG__ARM_CARTESIAN_COMMAND_REQUEST_ONE_OF_JOINT_CONFIGURATION_H_
