// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__ARM_SURFACE_CONTACT_REQUEST_ONE_OF_JOINT_CONFIGURATION_HPP_
#define BOSDYN_MSGS__MSG__ARM_SURFACE_CONTACT_REQUEST_ONE_OF_JOINT_CONFIGURATION_HPP_

#include "bosdyn_msgs/msg/detail/arm_surface_contact_request_one_of_joint_configuration__struct.hpp"
#include "bosdyn_msgs/msg/detail/arm_surface_contact_request_one_of_joint_configuration__builder.hpp"
#include "bosdyn_msgs/msg/detail/arm_surface_contact_request_one_of_joint_configuration__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__ARM_SURFACE_CONTACT_REQUEST_ONE_OF_JOINT_CONFIGURATION_HPP_
