// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/BodyExternalForceParamsExternalForceIndicator.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__BODY_EXTERNAL_FORCE_PARAMS_EXTERNAL_FORCE_INDICATOR_H_
#define BOSDYN_MSGS__MSG__BODY_EXTERNAL_FORCE_PARAMS_EXTERNAL_FORCE_INDICATOR_H_

#include "bosdyn_msgs/msg/detail/body_external_force_params_external_force_indicator__struct.h"
#include "bosdyn_msgs/msg/detail/body_external_force_params_external_force_indicator__functions.h"
#include "bosdyn_msgs/msg/detail/body_external_force_params_external_force_indicator__type_support.h"

#endif  // BOSDYN_MSGS__MSG__BODY_EXTERNAL_FORCE_PARAMS_EXTERNAL_FORCE_INDICATOR_H_
