// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__BODY_CONTROL_PARAMS_BODY_ASSIST_FOR_MANIPULATION_HPP_
#define BOSDYN_MSGS__MSG__BODY_CONTROL_PARAMS_BODY_ASSIST_FOR_MANIPULATION_HPP_

#include "bosdyn_msgs/msg/detail/body_control_params_body_assist_for_manipulation__struct.hpp"
#include "bosdyn_msgs/msg/detail/body_control_params_body_assist_for_manipulation__builder.hpp"
#include "bosdyn_msgs/msg/detail/body_control_params_body_assist_for_manipulation__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__BODY_CONTROL_PARAMS_BODY_ASSIST_FOR_MANIPULATION_HPP_
