// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_TARGET_POSITION_HPP_
#define BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_TARGET_POSITION_HPP_

#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_target_position__struct.hpp"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_target_position__builder.hpp"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_target_position__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_TARGET_POSITION_HPP_
