// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/ConstrainedManipulationCommandRequestControlMode.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_CONTROL_MODE_H_
#define BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_CONTROL_MODE_H_

#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_control_mode__struct.h"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_control_mode__functions.h"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_control_mode__type_support.h"

#endif  // BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_CONTROL_MODE_H_
