// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_TASK_TYPE_HPP_
#define BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_TASK_TYPE_HPP_

#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_task_type__struct.hpp"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_task_type__builder.hpp"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_task_type__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_TASK_TYPE_HPP_
