// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_SPEED_HPP_
#define BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_SPEED_HPP_

#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_speed__struct.hpp"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_speed__builder.hpp"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_speed__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_SPEED_HPP_
