// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/ConstrainedManipulationCommandRequestOneOfTaskSpeed.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_SPEED_H_
#define BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_SPEED_H_

#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_speed__struct.h"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_speed__functions.h"
#include "bosdyn_msgs/msg/detail/constrained_manipulation_command_request_one_of_task_speed__type_support.h"

#endif  // BOSDYN_MSGS__MSG__CONSTRAINED_MANIPULATION_COMMAND_REQUEST_ONE_OF_TASK_SPEED_H_
