// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__FAILURE_BEHAVIOR_RETURN_TO_START_AND_TRY_AGAIN_LATER_HPP_
#define BOSDYN_MSGS__MSG__FAILURE_BEHAVIOR_RETURN_TO_START_AND_TRY_AGAIN_LATER_HPP_

#include "bosdyn_msgs/msg/detail/failure_behavior_return_to_start_and_try_again_later__struct.hpp"
#include "bosdyn_msgs/msg/detail/failure_behavior_return_to_start_and_try_again_later__builder.hpp"
#include "bosdyn_msgs/msg/detail/failure_behavior_return_to_start_and_try_again_later__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__FAILURE_BEHAVIOR_RETURN_TO_START_AND_TRY_AGAIN_LATER_HPP_
