// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/FailureBehaviorReturnToStartAndTryAgainLater.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__FAILURE_BEHAVIOR_RETURN_TO_START_AND_TRY_AGAIN_LATER_H_
#define BOSDYN_MSGS__MSG__FAILURE_BEHAVIOR_RETURN_TO_START_AND_TRY_AGAIN_LATER_H_

#include "bosdyn_msgs/msg/detail/failure_behavior_return_to_start_and_try_again_later__struct.h"
#include "bosdyn_msgs/msg/detail/failure_behavior_return_to_start_and_try_again_later__functions.h"
#include "bosdyn_msgs/msg/detail/failure_behavior_return_to_start_and_try_again_later__type_support.h"

#endif  // BOSDYN_MSGS__MSG__FAILURE_BEHAVIOR_RETURN_TO_START_AND_TRY_AGAIN_LATER_H_
