// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__GET_BIT_STATUS_RESPONSE_DEGRADATION_DEGRADATION_TYPE_HPP_
#define BOSDYN_MSGS__MSG__GET_BIT_STATUS_RESPONSE_DEGRADATION_DEGRADATION_TYPE_HPP_

#include "bosdyn_msgs/msg/detail/get_bit_status_response_degradation_degradation_type__struct.hpp"
#include "bosdyn_msgs/msg/detail/get_bit_status_response_degradation_degradation_type__builder.hpp"
#include "bosdyn_msgs/msg/detail/get_bit_status_response_degradation_degradation_type__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__GET_BIT_STATUS_RESPONSE_DEGRADATION_DEGRADATION_TYPE_HPP_
