// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/GetBITStatusResponseDegradationDegradationType.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__GET_BIT_STATUS_RESPONSE_DEGRADATION_DEGRADATION_TYPE_H_
#define BOSDYN_MSGS__MSG__GET_BIT_STATUS_RESPONSE_DEGRADATION_DEGRADATION_TYPE_H_

#include "bosdyn_msgs/msg/detail/get_bit_status_response_degradation_degradation_type__struct.h"
#include "bosdyn_msgs/msg/detail/get_bit_status_response_degradation_degradation_type__functions.h"
#include "bosdyn_msgs/msg/detail/get_bit_status_response_degradation_degradation_type__type_support.h"

#endif  // BOSDYN_MSGS__MSG__GET_BIT_STATUS_RESPONSE_DEGRADATION_DEGRADATION_TYPE_H_
