// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__INVERSE_KINEMATICS_REQUEST_ONE_OF_STANCE_SPECIFICATION_HPP_
#define BOSDYN_MSGS__MSG__INVERSE_KINEMATICS_REQUEST_ONE_OF_STANCE_SPECIFICATION_HPP_

#include "bosdyn_msgs/msg/detail/inverse_kinematics_request_one_of_stance_specification__struct.hpp"
#include "bosdyn_msgs/msg/detail/inverse_kinematics_request_one_of_stance_specification__builder.hpp"
#include "bosdyn_msgs/msg/detail/inverse_kinematics_request_one_of_stance_specification__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__INVERSE_KINEMATICS_REQUEST_ONE_OF_STANCE_SPECIFICATION_HPP_
