// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/InverseKinematicsRequestOneOfTaskSpecification.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__INVERSE_KINEMATICS_REQUEST_ONE_OF_TASK_SPECIFICATION_H_
#define BOSDYN_MSGS__MSG__INVERSE_KINEMATICS_REQUEST_ONE_OF_TASK_SPECIFICATION_H_

#include "bosdyn_msgs/msg/detail/inverse_kinematics_request_one_of_task_specification__struct.h"
#include "bosdyn_msgs/msg/detail/inverse_kinematics_request_one_of_task_specification__functions.h"
#include "bosdyn_msgs/msg/detail/inverse_kinematics_request_one_of_task_specification__type_support.h"

#endif  // BOSDYN_MSGS__MSG__INVERSE_KINEMATICS_REQUEST_ONE_OF_TASK_SPECIFICATION_H_
