// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_HPP_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_HPP_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_navigation_feedback_response_active_region_information__struct.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_navigation_feedback_response_active_region_information__builder.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_navigation_feedback_response_active_region_information__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_HPP_
