// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_SERVICE_FAULT_SEVERITY_HPP_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_SERVICE_FAULT_SEVERITY_HPP_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_service_fault_severity__struct.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_service_fault_severity__builder.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_service_fault_severity__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_SERVICE_FAULT_SEVERITY_HPP_
