// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_FRAME_TREE_SNAPSHOT_PARENT_EDGE_HPP_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_FRAME_TREE_SNAPSHOT_PARENT_EDGE_HPP_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_frame_tree_snapshot_parent_edge__struct.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_frame_tree_snapshot_parent_edge__builder.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_frame_tree_snapshot_parent_edge__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_FRAME_TREE_SNAPSHOT_PARENT_EDGE_HPP_
