// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/KeyStringValueBosdynMsgsFrameTreeSnapshotParentEdge.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_FRAME_TREE_SNAPSHOT_PARENT_EDGE_H_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_FRAME_TREE_SNAPSHOT_PARENT_EDGE_H_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_frame_tree_snapshot_parent_edge__struct.h"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_frame_tree_snapshot_parent_edge__functions.h"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_frame_tree_snapshot_parent_edge__type_support.h"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_FRAME_TREE_SNAPSHOT_PARENT_EDGE_H_
