// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/KeyStringValueBosdynMsgsServiceFaultSeverity.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_SERVICE_FAULT_SEVERITY_H_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_SERVICE_FAULT_SEVERITY_H_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_service_fault_severity__struct.h"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_service_fault_severity__functions.h"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_service_fault_severity__type_support.h"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_SERVICE_FAULT_SEVERITY_H_
