// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_AREA_CALLBACK_ERROR_HPP_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_AREA_CALLBACK_ERROR_HPP_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_area_callback_error__struct.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_area_callback_error__builder.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_area_callback_error__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_AREA_CALLBACK_ERROR_HPP_
