// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_ONE_OF_PARAM_CHILD_SPEC_HPP_
#define BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_ONE_OF_PARAM_CHILD_SPEC_HPP_

#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_one_of_param_child_spec__struct.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_one_of_param_child_spec__builder.hpp"
#include "bosdyn_msgs/msg/detail/key_string_value_bosdyn_msgs_one_of_param_child_spec__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__KEY_STRING_VALUE_BOSDYN_MSGS_ONE_OF_PARAM_CHILD_SPEC_HPP_
