// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__MANIPULATION_API_REQUEST_ONE_OF_MANIPULATION_CMD_HPP_
#define BOSDYN_MSGS__MSG__MANIPULATION_API_REQUEST_ONE_OF_MANIPULATION_CMD_HPP_

#include "bosdyn_msgs/msg/detail/manipulation_api_request_one_of_manipulation_cmd__struct.hpp"
#include "bosdyn_msgs/msg/detail/manipulation_api_request_one_of_manipulation_cmd__builder.hpp"
#include "bosdyn_msgs/msg/detail/manipulation_api_request_one_of_manipulation_cmd__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__MANIPULATION_API_REQUEST_ONE_OF_MANIPULATION_CMD_HPP_
