// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ROUTE_FOLLOWING_STATUS_HPP_
#define BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ROUTE_FOLLOWING_STATUS_HPP_

#include "bosdyn_msgs/msg/detail/navigation_feedback_response_route_following_status__struct.hpp"
#include "bosdyn_msgs/msg/detail/navigation_feedback_response_route_following_status__builder.hpp"
#include "bosdyn_msgs/msg/detail/navigation_feedback_response_route_following_status__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ROUTE_FOLLOWING_STATUS_HPP_
