// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/NavigationFeedbackResponseActiveRegionInformationAreaCallbackStatus.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_AREA_CALLBACK_STATUS_H_
#define BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_AREA_CALLBACK_STATUS_H_

#include "bosdyn_msgs/msg/detail/navigation_feedback_response_active_region_information_area_callback_status__struct.h"
#include "bosdyn_msgs/msg/detail/navigation_feedback_response_active_region_information_area_callback_status__functions.h"
#include "bosdyn_msgs/msg/detail/navigation_feedback_response_active_region_information_area_callback_status__type_support.h"

#endif  // BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_AREA_CALLBACK_STATUS_H_
