// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/NavigationFeedbackResponseActiveRegionInformation.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_H_
#define BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_H_

#include "bosdyn_msgs/msg/detail/navigation_feedback_response_active_region_information__struct.h"
#include "bosdyn_msgs/msg/detail/navigation_feedback_response_active_region_information__functions.h"
#include "bosdyn_msgs/msg/detail/navigation_feedback_response_active_region_information__type_support.h"

#endif  // BOSDYN_MSGS__MSG__NAVIGATION_FEEDBACK_RESPONSE_ACTIVE_REGION_INFORMATION_H_
