// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/ProcessTopologyRequestOdometryLoopClosureParams.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__PROCESS_TOPOLOGY_REQUEST_ODOMETRY_LOOP_CLOSURE_PARAMS_H_
#define BOSDYN_MSGS__MSG__PROCESS_TOPOLOGY_REQUEST_ODOMETRY_LOOP_CLOSURE_PARAMS_H_

#include "bosdyn_msgs/msg/detail/process_topology_request_odometry_loop_closure_params__struct.h"
#include "bosdyn_msgs/msg/detail/process_topology_request_odometry_loop_closure_params__functions.h"
#include "bosdyn_msgs/msg/detail/process_topology_request_odometry_loop_closure_params__type_support.h"

#endif  // BOSDYN_MSGS__MSG__PROCESS_TOPOLOGY_REQUEST_ODOMETRY_LOOP_CLOSURE_PARAMS_H_
