// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__PROCESS_ANCHORING_REQUEST_PARAMS_OPTIMIZER_PARAMS_HPP_
#define BOSDYN_MSGS__MSG__PROCESS_ANCHORING_REQUEST_PARAMS_OPTIMIZER_PARAMS_HPP_

#include "bosdyn_msgs/msg/detail/process_anchoring_request_params_optimizer_params__struct.hpp"
#include "bosdyn_msgs/msg/detail/process_anchoring_request_params_optimizer_params__builder.hpp"
#include "bosdyn_msgs/msg/detail/process_anchoring_request_params_optimizer_params__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__PROCESS_ANCHORING_REQUEST_PARAMS_OPTIMIZER_PARAMS_HPP_
