// generated from rosidl_generator_c/resource/idl.h.em
// with input from bosdyn_msgs:msg/ProcessAnchoringRequestParamsMeasurementParams.idl
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__PROCESS_ANCHORING_REQUEST_PARAMS_MEASUREMENT_PARAMS_H_
#define BOSDYN_MSGS__MSG__PROCESS_ANCHORING_REQUEST_PARAMS_MEASUREMENT_PARAMS_H_

#include "bosdyn_msgs/msg/detail/process_anchoring_request_params_measurement_params__struct.h"
#include "bosdyn_msgs/msg/detail/process_anchoring_request_params_measurement_params__functions.h"
#include "bosdyn_msgs/msg/detail/process_anchoring_request_params_measurement_params__type_support.h"

#endif  // BOSDYN_MSGS__MSG__PROCESS_ANCHORING_REQUEST_PARAMS_MEASUREMENT_PARAMS_H_
