// generated from rosidl_generator_cpp/resource/idl.hpp.em
// generated code does not contain a copyright notice

#ifndef BOSDYN_MSGS__MSG__UPDATE_CALLBACK_RESPONSE_UPDATE_LOCALIZATION_LOCALIZATION_CHANGE_HPP_
#define BOSDYN_MSGS__MSG__UPDATE_CALLBACK_RESPONSE_UPDATE_LOCALIZATION_LOCALIZATION_CHANGE_HPP_

#include "bosdyn_msgs/msg/detail/update_callback_response_update_localization_localization_change__struct.hpp"
#include "bosdyn_msgs/msg/detail/update_callback_response_update_localization_localization_change__builder.hpp"
#include "bosdyn_msgs/msg/detail/update_callback_response_update_localization_localization_change__traits.hpp"

#endif  // BOSDYN_MSGS__MSG__UPDATE_CALLBACK_RESPONSE_UPDATE_LOCALIZATION_LOCALIZATION_CHANGE_HPP_
