name: bosdyn_msgs CD

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-bundles:
    strategy:
      matrix:
        config:
        - { runner: "ubuntu-22-04-large-runner", arch: "amd64" }
        - { runner: "k8s-t2a-standard-16", arch: "arm64" }
    name: Build ${{ matrix.config.arch }} Bundles
    runs-on: ${{ matrix.config.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build bosdyn_msgs bundles
        run: make -j VERSION=${{ github.ref_name }} ${{ matrix.config.arch }}

      - name: Upload bundle artifact for ${{ matrix.config.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.arch }}
          path: '*.run'

  release-bundles:
    name: Release Bundles
    runs-on: ubuntu-latest
    needs: [build-bundles] 
    steps:
      - name: Download bundles
        uses: actions/download-artifact@v4
        with:
          # With no `name` specified all artifacts for the run are downloaded.
          pattern: '*.run'
          merge-multiple: true

      - name: Release bosdyn_msgs bundles
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: '*.run'
