name: bosdyn_msgs CD

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release-bundles:
    runs-on:
      group: k8s-t2a-standard-16
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true 
      
      - name: Build bosdyn_msgs bundles
        run: make -j8 VERSION=${{ github.ref_name }}
      
      - name: Release bosdyn_msgs bundles
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: '*.run'
