name: bosdyn_msgs CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        config:
        - { runner: "k8s-n1-standard-16", image: "ros:humble-ros-base-jammy", arch: "amd64" }
        - { runner: "k8s-t2a-standard-16", image: "arm64v8/ros:humble-ros-base-jammy", arch: "arm64" }
    name: Build and test bosdyn_msgs packages for ${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.runner }}
    container:
      image: ${{ matrix.config.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: src/bosdyn_msgs
          submodules: true
      - name: Install dependencies
        run: |
          apt update && apt install -y python3-pip wget
          export PIP_CONSTRAINT=src/bosdyn_msgs/pip-constraint.txt
          rosdep update && rosdep install -i -y --from-path src --skip-keys "$(cat src/bosdyn_msgs/rosdep-skip.txt)"
          for url in $(cat src/bosdyn_msgs/${{ matrix.config.arch }}-dpkg.txt); do 
            wget $url && apt install -y ./$(basename $url);
          done 
      - name: Build and run tests for ${{ matrix.config.arch }}
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --packages-up-to bosdyn_msgs
          colcon test --event-handlers console_direct+ --packages-up-to bosdyn_msgs
          colcon test-result --all --verbose  # to ensure the job fails if any test does
