name: bosdyn_msgs CI

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    name: Build and test bosdyn_msgs packages
    runs-on: ubuntu-latest
    container:
      image: ros:humble-ros-base-jammy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: src/bosdyn_msgs
      - name: Install dependencies
        run: |
          apt update && apt install -y python3-pip
          export PIP_CONSTRAINT=src/bosdyn_msgs/.tooling/pip/constraint.txt
          rosdep update && rosdep install -i -y --from-path src
      - name: Build and run tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --symlink-install --packages-up-to bosdyn_msgs
          colcon test --event-handlers console_direct+
          colcon test-result --all --verbose
