name: bosdyn_msgs mirroring

on:
  push:
    branches: main
    tags:
      - '*'

env:
  # github.repository as <account>/<repo>
  MIRROR_REPOSITORY: bdaiinstitute/bosdyn_msgs

jobs:
  mirror-repo:
    name: Mirror bosdyn_msgs repository
    runs-on: ubuntu-22-04-large-runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false
      - name: Push to mirror repository
        run: |
          git push --tags --follow-tags --recurse-submodules=on-demand \
          https://${{ secrets.MIRROR_USERNAME }}:${{ secrets.MIRROR_PAT }}@github.com/${{ env.MIRROR_REPOSITORY }}.git \
          HEAD:main
