name: bosdyn_msgs release mirroring

on:
  workflow_dispatch:
  workflow_run:
    workflows: [bosdyn_msgs CD]
    types: [completed]
  release:
    types: [published]

env:
  # github.repository as <account>/<repo>
  MIRROR_REPOSITORY: bdaiinstitute/bosdyn_msgs

jobs:
  mirror-latest-release:
    name: Mirror latest bosdyn_msgs release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Pull release assets
        uses: robinraju/release-downloader@v1.9
        id: download
        with:
          latest: true
          fileName: '*.run'
      - name: Create mirror release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.download.outputs.release_name }}
          repository: ${{ env.MIRROR_REPOSITORY }}
          token: ${{ secrets.MIRROR_PAT }}
          tag_name: ${{ steps.download.outputs.tag_name }}
          files: '*.run'
  mirror-published-release:
    name: Mirror published bosdyn_msgs release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    permissions:
      contents: write
    steps:
      - name: Pull release assets
        uses: robinraju/release-downloader@v1.9
        id: download
        with:
          tag: ${{ github.ref_name }}
          fileName: '*.run'
      - name: Create mirror release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.download.outputs.release_name }}
          repository: ${{ env.MIRROR_REPOSITORY }}
          token: ${{ secrets.MIRROR_PAT }}
          tag_name: ${{ steps.download.outputs.tag_name }}
          files: '*.run'
