name: bosdyn_msgs release workflow

on:
  push:
    tags:
      - '*'

jobs:
  release-bundles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build bosdyn_msgs bundle
        run: make -j8 VERSION=${{ github.ref_name }}
      - name: Release bosdyn_msgs bundles
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: '*.run'
